### ISSUE TITLE
订阅检查更新问题-b站直播开播路由

### ISSUE THREAD

**Issue by Matt-Shiro** [Quan666/ELF_RSS#108]
Version: v2.2.2
订阅哔哩哔哩直播开播路由时，运行出现重复“{rss.name}第一次抓取成功”问题。
![question](https://user-images.githubusercontent.com/32786764/119239242-5caa4900-bb7a-11eb-8683-ec2ff0665ab2.png)
附上测试用RSS订阅（不让上传json，改成txt上传了）
[rss.txt](https://github.com/Quan666/ELF_RSS/files/6527046/rss.txt)

**Comment by NekoAria** [comment]
先升级到 v2.2.2-fix 看看吧。
如果还有问题，那就要发新版本了。
仓库里最新的代码是正常的。

**Comment by Matt-Shiro** [comment]
v2.2.2-fix问题解决，谢谢！
