### ISSUE TITLE
Debian 10 + go-cqhttp 图片处理异常

### ISSUE THREAD

**Issue by NekoAria** [Quan666/ELF_RSS#12]
https://github.com/Quan666/ELF_RSS/blob/cf08ca9672b7f665e6fedea0458c09578fe1011d/include/plugins/RSSHub/rsshub.py#L297-L302

这段代码只保留最后一行，就能正常发送图片了。
CQ码发送本地图片都是需要File URI的，这点应该是平台无关。
我看过[之前关闭了的一个issue](https://github.com/Quan666/ELF_RSS/issues/7)，不知道@OmaruPolka 在那之后是否也遇到我这个情况。

**Comment by Quan666** [comment]
能否将完整的报错日志发上来

**Comment by NekoAria** [comment]
ELF_RSS的日志：
`
[2020-08-24 16:19:41,929 nonebot] INFO: 检查 yande.re_1d 更新
49
50

[CQ:image,file=/root/ELF_RSS/data/imgs/b1878291-e336-48b3-a6c0-775eb3c70d06.jpg]Rating:q Score:42
`

go-cqhttp的日志：
`
[2020-08-24 16:19:44] [DEBUG]: WS接收到API调用: send_msg 参数: {"message_type": "private", "user_id": "*", "message": "\u3010Last 24 hours - yande.re\u3011\u66f4\u65b0\u4e86!\n----------------------\n\u5185\u5bb9\uff1a[CQ:image,file=/root/ELF_RSS/data/imgs/b1878291-e336-48b3-a6c0-775eb3c70d06.jpg]Rating:q Score:42\n\u539f\u94fe\u63a5\uff1ahttps://yande.re/post/show/673805\n\u65e5\u671f\uff1a08\u670820\u65e5 05:12:48"}
[2020-08-24 16:19:44] [WARNING]: 转换CQ码到MiraiGo Element时出现错误: invalid image 将原样发送.
`

**Comment by Quan666** [comment]
你把isLinux关了能正常吗？

**Comment by Quan666** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/169 可能是这个

**Comment by NekoAria** [comment]
我觉得更像是[转义处理](https://github.com/Mrs4s/go-cqhttp/issues/9)这出的问题。

我找了之前把isLinux设为false后的日志：

ELF_RSS的日志：

> [2020-08-24 12:17:53,835 nonebot] INFO: 检查 yande.re_1d 更新
> 45
> 48
> 
> [CQ:image,file=file:///\root\ELF_RSS\data\imgs\b7fb997b-f760-42fc-ba42-4f80cc1a613c.jpg]Rating:e Score:40

go-cqhttp的日志：

> [2020-08-24 12:17:56] [DEBUG]: WS接收到API调用: send_msg 参数: {"message_type": "private", "user_id": "990879119", "message": "\u3010Last 24 hours - yande.re\u3011\u66f4\u65b0\u4e86!\n----------------------\n\u5185\u5bb9\uff1a[CQ:image,file=file:///\\root\\ELF_RSS\\data\\imgs\\b7fb997b-f760-42fc-ba42-4f80cc1a613c.jpg]Rating:e Score:40\n\u539f\u94fe\u63a5\uff1ahttps://yande.re/post/show/675373\n\u65e5\u671f\uff1a08\u670823\u65e5 23:13:12"}
> [2020-08-24 12:17:56] [WARNING]: 转换CQ码到MiraiGo Element时出现错误: open /\root\ELF_RSS\data\imgs\b7fb997b-f760-42fc-ba42-4f80cc1a613c.jpg: no such file or directory 将原样发送.

**Comment by NekoAria** [comment]
我觉得更像是[转义处理](https://github.com/Mrs4s/go-cqhttp/issues/9)这出的问题。

我找了之前把isLinux设为false后的日志：

ELF_RSS的日志：

> [2020-08-24 12:17:53,835 nonebot] INFO: 检查 yande.re_1d 更新
> 45
> 48
> 
> [CQ:image,file=file:///\root\ELF_RSS\data\imgs\b7fb997b-f760-42fc-ba42-4f80cc1a613c.jpg]Rating:e Score:40

go-cqhttp的日志：

> [2020-08-24 12:17:56] [DEBUG]: WS接收到API调用: send_msg 参数: {"message_type": "private", "user_id": "*", "message": "\u3010Last 24 hours - yande.re\u3011\u66f4\u65b0\u4e86!\n----------------------\n\u5185\u5bb9\uff1a[CQ:image,file=file:///\\root\\ELF_RSS\\data\\imgs\\b7fb997b-f760-42fc-ba42-4f80cc1a613c.jpg]Rating:e Score:40\n\u539f\u94fe\u63a5\uff1ahttps://yande.re/post/show/675373\n\u65e5\u671f\uff1a08\u670823\u65e5 23:13:12"}
> [2020-08-24 12:17:56] [WARNING]: 转换CQ码到MiraiGo Element时出现错误: open /\root\ELF_RSS\data\imgs\b7fb997b-f760-42fc-ba42-4f80cc1a613c.jpg: no such file or directory 将原样发送.

**Comment by NekoAria** [comment]
PS：

[OneBot 标准中消息段类型部分有提到：](https://github.com/howmanybots/onebot/blob/master/v11/specs/message/segment.md)

> 发送时，`file` 参数除了支持使用收到的图片文件名直接发送外，还支持：
> 绝对路径，例如 `file:///C:\\Users\Richard\Pictures\1.png`，格式使用 [file URI](https://tools.ietf.org/html/rfc8089)
> 网络 URL，例如 `http://i1.piimg.com/567571/fdd6e7b6d93f1ef0.jpg`
> Base64 编码，例如 `base64://iVBORw0KGgoAAAANSUhEUgAAABQAAAAVCAIAAADJt1n/AAAAKElEQVQ4EWPk5+RmIBcwkasRpG9UM4mhNxpgowFGMARGEwnBIEJVAAAdBgBNAZf+QAAAAABJRU5ErkJggg==`

go-cqhttp是按照这个标准走的，至于cqhttp-mirai，我就不是很清楚了，~~源码读起来头大~~。😭️

**Comment by Quan666** [comment]
试试最新版本 https://github.com/Quan666/ELF_RSS/commit/aefcd1356d58dd480e25adbf665c562721099eb1

**Comment by NekoAria** [comment]
试过了，同样报错。

go-cqhttp的日志：

> [2020-08-26 16:25:00] [DEBUG]: WS接收到API调用: send_msg 参数: {"message_type":"private","user_id":"990879119","message":"\u3010Last week - yande.re\u3011\u66f4\u65b0\u4e86!\n----------------------\n\u5185\u5bb9\uff1a[CQ:image,file=\/root\/ELF_RSS\/data\/imgs\/bcff7cbe489f4da28de4f4a40176bcd2.jpg]Rating:q Score:85\n\u539f\u94fe\u63a5\uff1ahttps:\/\/yande.re\/post\/show\/673799\n\u65e5\u671f\uff1a08\u670820\u65e5 05:12:24"}
> [2020-08-26 16:25:00] [WARNING]: 转换CQ码 [CQ:image,file=/root/ELF_RSS/data/imgs/bcff7cbe489f4da28de4f4a40176bcd2.jpg] 到MiraiGo Element时出现错误: invalid image 将原样发送.

为什么不采纳我一开始的提议呢？至少问题在我这是解决了。而且file URI是不可或缺的。

**Comment by NekoAria** [comment]
试过了，同样报错。

go-cqhttp的日志：

> [2020-08-26 16:25:00] [DEBUG]: WS接收到API调用: send_msg 参数: {"message_type":"private","user_id":"*","message":"\u3010Last week - yande.re\u3011\u66f4\u65b0\u4e86!\n----------------------\n\u5185\u5bb9\uff1a[CQ:image,file=\/root\/ELF_RSS\/data\/imgs\/bcff7cbe489f4da28de4f4a40176bcd2.jpg]Rating:q Score:85\n\u539f\u94fe\u63a5\uff1ahttps:\/\/yande.re\/post\/show\/673799\n\u65e5\u671f\uff1a08\u670820\u65e5 05:12:24"}
> [2020-08-26 16:25:00] [WARNING]: 转换CQ码 [CQ:image,file=/root/ELF_RSS/data/imgs/bcff7cbe489f4da28de4f4a40176bcd2.jpg] 到MiraiGo Element时出现错误: invalid image 将原样发送.

为什么不采纳我一开始的提议呢？至少问题在我这是解决了。而且file URI是不可或缺的。

**Comment by NekoAria** [comment]
https://github.com/Quan666/ELF_RSS/blob/cf08ca9672b7f665e6fedea0458c09578fe1011d/include/plugins/RSSHub/rsshub.py#L314-L317

另外我注意到处理视频的部分，代码看起来是直接copy了处理图片那段，完全一致。

**Comment by Quan666** [comment]
看来是我考虑过多了
