### ISSUE TITLE
关于BOT无法启动的请教

### ISSUE THREAD

**Issue by YokiiroBW** [Quan666/ELF_RSS#136]
前两天重启了下服务器，然后bot就启动不起来了。一直提示找不到nonebot.log
![image](https://user-images.githubusercontent.com/82425598/121062740-0edb4500-c7f8-11eb-8920-39ffc354b2b1.png)

我想重新安装下依赖，但是不知道为啥我现在的pip都用不了了，一直提示超时，换了下载源也不行，求指教。
![image](https://user-images.githubusercontent.com/82425598/121062866-2f0b0400-c7f8-11eb-8531-a57b614ad7c8.png)

**Comment by Quan666** [comment]
把代理软件关了再安装依赖。如果还是报错建议重新安装Python

**Comment by YokiiroBW** [comment]
最后重装了Python，解决了，非常感谢
