### ISSUE TITLE
图片抓取失败，代理正常

### ISSUE THREAD

**Issue by yoiyami96** [Quan666/ELF_RSS#148]
elf-rss版本2.2.6，代理软件已开，浏览器可正常访问推特
rss链接：Name：推特like
                URL：https://rss.shab.fun/twitter/likes/leere1030

日志：
06-30 18:37:00 [WARNING] nonebot | 推特like 抓取失败！将重试最多 5 次！
06-30 18:37:14 [ERROR] nonebot | 图片[https://pbs.twimg.com/media/E5H5jiNUUAAaSh
R.jpg:orig]下载失败,有可能需要开启代理！
[WinError 121] 信号灯超时时间已到
06-30 18:37:22 [ERROR] nonebot | 图片[https://pbs.twimg.com/media/E5HzstNVUAY_Uq
-.jpg:orig]下载失败,有可能需要开启代理！
[WinError 121] 信号灯超时时间已到
06-30 18:37:35 [ERROR] nonebot | 图片[https://pbs.twimg.com/media/E5H5ji7VkAMDyg
R.jpg:orig]下载失败,有可能需要开启代理！
[WinError 121] 信号灯超时时间已到
06-30 18:37:56 [ERROR] nonebot | 图片[https://pbs.twimg.com/media/E5H5jjmVgAgmqE
-.jpg:orig]下载失败,有可能需要开启代理！
[WinError 121] 信号灯超时时间已到
06-30 18:37:56 [INFO] nonebot | 我的推特 新消息推送完毕，共计：1
06-30 18:38:03 [ERROR] nonebot | 图片[https://pbs.twimg.com/media/E5H5jiNUUAAaSh
R.jpg:orig]下载失败,有可能需要开启代理！
[WinError 121] 信号灯超时时间已到
06-30 18:38:24 [ERROR] nonebot | 图片[https://pbs.twimg.com/media/E5H5ji7VkAMDyg
R.jpg:orig]下载失败,有可能需要开启代理！
[WinError 121] 信号灯超时时间已到
06-30 18:38:45 [ERROR] nonebot | 图片[https://pbs.twimg.com/media/E5H5jjmVgAgmqE
-.jpg:orig]下载失败,有可能需要开启代理！
[WinError 121] 信号灯超时时间已到
06-30 18:38:46 [INFO] nonebot | 推特like 新消息推送完毕，共计：2

**Comment by Quan666** [comment]
你这个订阅的代理没打开吧

**Comment by yoiyami96** [comment]
> 你这个订阅的代理没打开吧

靠，被自己弱智到，对不起打扰了
