### ISSUE TITLE
新版使用第三方自定义微博rss时,被##包含的链接会显示出来.

### ISSUE THREAD

**Issue by Ticysis** [Quan666/ELF_RSS#16]
就像这样.
https://s1.ax1x.com/2020/10/09/0B5hnJ.png
..
..
issues能直接贴图片嘛,第一次提,不是很熟悉QAQ~.

**Comment by Ticysis** [comment]
这个rss,未更新前好像时 ## 内的内容是正常显示的.
https://rssfeed.today/weibo/

**Comment by Quan666** [comment]
请发送正确的rss订阅地址

**Comment by Ticysis** [comment]
图片中的rss
https://rssfeed.today/weibo/rss/6603867494

**Comment by Quan666** [comment]
没有复现，可能是概率问题，当作没发生过吧，2333
