### ISSUE TITLE
无法安装插件

### ISSUE THREAD

**Issue by yuanzhidao** [Quan666/ELF_RSS#175]
'''
[root@VM-8-4-centos iYuan-Bot]# nb plugin install ELF_RSS2
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting ELF-RSS
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/be/c8/477e0a6f91b517e1eeaf9135f22009b1cfa42eaafb4e680fcfd9cdfee16a/ELF_RSS-2.3.0.tar.gz (34 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/be/c8/477e0a6f91b517e1eeaf9135f22009b1cfa42eaafb4e680fcfd9cdfee16a/ELF_RSS-2.3.0.tar.gz#sha256=f4815857ea991aa63bb9750d1b9c02225e3b098ab3c870d6102b4d26c6ce1eb2 (from https://pypi.tuna.tsinghua.edu.cn/simple/elf-rss/). Requested ELF-RSS from https://pypi.tuna.tsinghua.edu.cn/packages/be/c8/477e0a6f91b517e1eeaf9135f22009b1cfa42eaafb4e680fcfd9cdfee16a/ELF_RSS-2.3.0.tar.gz#sha256=f4815857ea991aa63bb9750d1b9c02225e3b098ab3c870d6102b4d26c6ce1eb2 has inconsistent version: filename has '2.3.0', but metadata has '2.0.0'
ERROR: Could not find a version that satisfies the requirement ELF-RSS (from versions: 2.3.0)
ERROR: No matching distribution found for ELF-RSS
'''

**Comment by Quan666** [comment]
建议先自己下载了安装，回头我修复下这个问题

**Comment by Quan666** [comment]
把`pyproject.toml`文件改成这样再试试
https://github.com/Quan666/ELF_RSS/blob/c24cefe85b9d38ce32e90064cc9fe22ff1f12df4/pyproject.toml#L3
