### ISSUE TITLE
在QQ群中发出的消息中若包含分割线“-------”，账户会被风控

### ISSUE THREAD

**Issue by sparkcyf** [Quan666/ELF_RSS#178]
## 发生了什么

新配置的账户无法在QQ群中推送RSS信息。

## 定位过程

尝试使用go-cqhttp的api功能手动发出推送，最后定位到如果消息包含BOT消息模版中的分割线`----------------------`，则消息会出发风控，无法在群中发出。

https://github.com/Quan666/ELF_RSS/blob/bd396ee89b07b67843088089bec713f8a3f836c0/src/plugins/ELF_RSS2/RSS/routes/Parsing/__init__.py#L222

## 临时解决方案

暂时将分割线去除，或更换为波浪线`~~~~~~~`

**Comment by Quan666** [comment]
能否将被风控的消息发出来看看

**Comment by sparkcyf** [comment]
> 能否将被风控的消息发出来看看


其他信息：
- 纯文字消息，没有附带图片
- 设备使用的是手表协议，二维码登录
- QQ号已经注册了一年多了，一天前使用 go-cqhttp 登陆。

```
【妮可牛娃论坛 - 最新话题】更新了! 
 ----------------------
 标题：关于找老师的问题 
 链接：https://niko.cra.moe/t/topic/469 
 日期：09月03日 09:02:22
```

**Comment by Quan666** [comment]
是用的最新版本的 go-cqhttp 吗？
还是第一次遇到因为这个风控的

**Comment by sparkcyf** [comment]
是的，用的 [v1.0.0-beta6](https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-beta6) 。

另外据观察，如果在消息中使用了超过6个连续的波浪线（`~~~~~~`）也会出发风控，小于等于5个则可以，有些怀疑是QQ对于消息中存在的连续的标点符号有一些风控策略。

**Comment by Quan666** [comment]
emmm，那我改成4个

**Comment by sparkcyf** [comment]
已经确认四个连字符或者波浪线都能正常发送

```
curl -vvv -H "Content-Type:application/json" -d '{"message_type":"group","group_id":"114514", "message":"【妮可牛娃论坛 - 最新话题】更新了! \n ---- \n 标题：关于找老师的问题 \n 链接：https://niko.cra.moe/t/topic/469 \n 日期：09月03日 09:02:22","auto_escape":true}' http://127.0.0.1:5700/send_msg
*   Trying 127.0.0.1:5700...
* Connected to 127.0.0.1 (127.0.0.1) port 5700 (#0)
> POST /send_msg HTTP/1.1
> Host: 127.0.0.1:5700
> User-Agent: curl/7.74.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 251
> 
* upload completely sent off: 251 out of 251 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Fri, 03 Sep 2021 03:26:10 GMT
< Content-Length: 61
< 
{"data":{"message_id":1919810},"retcode":0,"status":"ok"}
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by Quan666** [comment]
你开了消息分片没

**Comment by sparkcyf** [comment]
没有打开

**Comment by Quan666** [comment]
打开试试

**Comment by sparkcyf** [comment]
开启 `force-fragment` 之后，看起来是能够发送长的分割线了。

https://github.com/Mrs4s/go-cqhttp/blob/6c52734324bb28d84a59f7f7d0d393841225b5e9/global/config/default_config.yml#L31

**Comment by Quan666** [comment]
那就应该是消息太长导致的风控

**Comment by sparkcyf** [comment]
好吧，那之后我默认把`force-fragment`打开。

（另外请问这个选项在未来需要变成推荐设置吗？）

**Comment by Quan666** [comment]
go-cqhttp 是推荐开启消息分片的

**Comment by sparkcyf** [comment]
好的，感谢！
