### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by fatinghenji** [Quan666/ELF_RSS#187]
![image](https://user-images.githubusercontent.com/37131177/133489594-c12313f6-4619-43da-abc2-fd5ac8590c81.png)

**Comment by NekoAria** [comment]
这个报错信息很明显啊，你配置文件没改。
首先要复制一份 `.env.dev` ，重命名为 `.env.prod` ，然后改这一行：
```
SUPERUSERS=["123123123"]  # 配置 NoneBot 超级用户：管理员qq，支持多管理员，逗号分隔 注意，启动消息只发送给第一个管理员
```

**Comment by fatinghenji** [comment]
> 这个报错信息很明显啊，你配置文件没改。
> 首先要复制一份 `.env.dev` ，重命名为 `.env.prod` ，然后改这一行：
> 
> ```
> SUPERUSERS=["123123123"]  # 配置 NoneBot 超级用户：管理员qq，支持多管理员，逗号分隔 注意，启动消息只发送给第一个管理员
> ```

感谢解答，但是我的`.env.dev`文件中没有所提到的那一行
![image](https://user-images.githubusercontent.com/37131177/133490710-68d4801f-d66c-4155-a0a8-c7902f72a815.png)

**Comment by NekoAria** [comment]
> > 这个报错信息很明显啊，你配置文件没改。
> > 首先要复制一份 `.env.dev` ，重命名为 `.env.prod` ，然后改这一行：
> > ```
> > SUPERUSERS=["123123123"]  # 配置 NoneBot 超级用户：管理员qq，支持多管理员，逗号分隔 注意，启动消息只发送给第一个管理员
> > ```
> 
> 感谢解答，但是我的`.env.dev`文件中没有所提到的那一行
> ![image](https://user-images.githubusercontent.com/37131177/133490710-68d4801f-d66c-4155-a0a8-c7902f72a815.png)

你这个是通过 `nb plugin install ELF_RSS2` 安装的吗？
那需要从这个仓库复制一下 `.env.dev` 的内容到 `.env.prod` 里。

**Comment by NekoAria** [comment]
另外说一句，目前还没更新到 `V2.4.1` ，当前仓库里最新的 `V2.4.0` 有点问题。
建议等到 @Quan666  发布 `V2.4.1` 之后再部署 ELF_RSS 。

**Comment by fatinghenji** [comment]
> > > 这个报错信息很明显啊，你配置文件没改。
> > > 首先要复制一份 `.env.dev` ，重命名为 `.env.prod` ，然后改这一行：
> > > ```
> > > SUPERUSERS=["123123123"]  # 配置 NoneBot 超级用户：管理员qq，支持多管理员，逗号分隔 注意，启动消息只发送给第一个管理员
> > > ```
> > 
> > 
> > 感谢解答，但是我的`.env.dev`文件中没有所提到的那一行
> > ![image](https://user-images.githubusercontent.com/37131177/133490710-68d4801f-d66c-4155-a0a8-c7902f72a815.png)
> 
> 你这个是通过 `nb plugin install ELF_RSS2` 安装的吗？
> 那需要从这个仓库复制一下 `.env.dev` 的内容到 `.env.prod` 里。

![image](https://user-images.githubusercontent.com/37131177/133494452-e5c7fcaa-ee7a-4871-b37f-5d4f8c084853.png)
修改相关文件后报错（
但是收到了启动消息
![image](https://user-images.githubusercontent.com/37131177/133494728-032a6d5d-e48f-4233-a8d7-e5b2b95bdce9.png)

**Comment by NekoAria** [comment]
如果方便的话请直接加群：984827132
因为 `V2.4.0` 改动挺多，而且没怎么测试新用户会遇到什么问题……
也就麻烦你帮忙测试，发现有什么问题我们好马上解决了。

**Comment by fatinghenji** [comment]
> 如果方便的话请直接加群：984827132
> 因为 `V2.4.0` 改动挺多，而且没怎么测试新用户会遇到什么问题……
> 也就麻烦你帮忙测试，发现有什么问题我们好马上解决了。

已经申请了，没有通过

**Comment by NekoAria** [comment]
> > 如果方便的话请直接加群：984827132
> > 因为 `V2.4.0` 改动挺多，而且没怎么测试新用户会遇到什么问题……
> > 也就麻烦你帮忙测试，发现有什么问题我们好马上解决了。
> 
> 已经申请了，没有通过

群主和管理员都睡了吧，只能等了。

**Comment by fatinghenji** [comment]
问题解决，关闭
