### ISSUE TITLE
Some suggestions on deployment

### ISSUE THREAD

**Issue by OmaruPolka** [Quan666/ELF_RSS#19]
1. 依赖部分
```
idna==2.5   requests==1.21.1
```
缺少```ujson```和```msgpack```依赖

2.适配Python3.9（？
```
sed -i 's/base64.decodestring/base64.decodebytes/g' ${work dir}/${venv name}/lib/python3.9/site-packages/feedparser.py
```
以上是暂时的解决方法 记得自行更换目录

**Comment by Quan666** [comment]
1. 依赖文件是自动生成的，缺少ujson和msgpack好像并不影响正常使用。requests 项目是 2.21.1 版本，不考虑降级。idna不知道具体作用。
2. 暂时不考虑适配python 3.9
