### ISSUE TITLE
部署之后无法订阅

### ISSUE THREAD

**Issue by wsmnwc** [Quan666/ELF_RSS#20]
大佬你好，我在这方面是纯小白，刚开始学习Bot的部署方法，翻阅了issue和部署教程仍然存在一些疑问，烦请大佬解答，非常感谢

已经按照部署流程部署 ELF_RSS，迁移到go-cqhttp后，在两者都运行的情况下可以看到bot接收到了消息：
![image](https://user-images.githubusercontent.com/24580021/99689449-5b646a80-2aca-11eb-989e-e1b2e12f03fd.png)

### 插件配置如图：
![image](https://user-images.githubusercontent.com/24580021/99690231-420fee00-2acb-11eb-99c9-e471458ef842.png)

但是之后依照使用方法向bot发送add等命令都没有回应，请问还需进行哪些步骤

**Comment by Quan666** [comment]
你这是少装了个module，运行 `pip3 install base64` 再试试

**Comment by wsmnwc** [comment]
> 你这是少装了个module，运行 `pip3 install base64` 再试试

感谢您的回复！尝试运行之后报错：
ERROR: Could not find a version that satisfies the requirement base64 (from versions: none)
ERROR: No matching distribution found for base64

查了一下有说是网络问题的，也有说pip版本需要更新，然后分别执行了
`python -m pip install --upgrade pip`和
`pip install base64 -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com`   
![image](https://user-images.githubusercontent.com/24580021/99782316-4e905700-2b5c-11eb-989a-74f34ea0923e.png)
![image](https://user-images.githubusercontent.com/24580021/99782367-5d770980-2b5c-11eb-8989-5371b0327028.png)

### 另外看到有人说模块名是pybase64，安装结果如下：
![image](https://user-images.githubusercontent.com/24580021/99782916-1d645680-2b5d-11eb-8aa4-657fd36c2a66.png)

重新启动了ELF_RSS和go-cqhttp后还是没反应...

**Comment by wsmnwc** [comment]
> 你这是少装了个module，运行 `pip3 install base64` 再试试

参考了一下[这里](https://github.com/pcrbot/yobot/issues/193)的解决方法，应该是Py3.9的原因：

> 这个问题是 yobot 的一个依赖 feedparser 5.* 版本未适配 python3.9 导致的，更新到 feedparser 到 6.* 即可解决

运行了`pip3 install feedparser~=6.0`之后问题解决了，再次感谢

**Comment by wsmnwc** [comment]
还有一处问题是，我尝试了数十次订阅，都说参数不正确，应该是按照要求写的：

![image](https://user-images.githubusercontent.com/24580021/99791060-65d54180-2b68-11eb-8b88-6b63920cd954.png)

![image](https://user-images.githubusercontent.com/24580021/99790922-2c9cd180-2b68-11eb-975e-18deb493b931.png)

**Comment by Quan666** [comment]
订阅源是rsshub时，应该以`/`开头。

**Comment by wsmnwc** [comment]
> 订阅源是rsshub时，应该以`/`开头。

感谢您的回复，不过我截图有几条加了`/`的当时也失败了，格式应该没问题，刚才又重试了一次，这次看到命令行里返回了订阅成功，但是之后bot就卡死了...Ctrl+C也结束不了
![image](https://user-images.githubusercontent.com/24580021/99872187-451df200-2c23-11eb-8a05-5f1ab7ff3e5d.png)

我重新部署一遍试试

**Comment by Quan666** [comment]
卡死的时候尝试回车试下，有时候是Windows powershell 快速编辑模式的锅

**Comment by wsmnwc** [comment]
> 卡死的时候尝试回车试下，有时候是Windows powershell 快速编辑模式的锅

应该不是您描述的这类情况，看了下Python占用内存飙升，而且bot对后续的命令也没反应了，估计是我昨天动了什么地方导致依赖出问题了

**Comment by Quan666** [comment]
你用的是Python3.9吗？那建议退回3.8

**Comment by wsmnwc** [comment]
> 你用的是Python3.9吗？那建议退回3.8

了解！回头试试看，感谢解答
