### ISSUE TITLE
不能正常推送消息

### ISSUE THREAD

**Issue by fatinghenji** [Quan666/ELF_RSS#200]
showall或其他命令正常
可以增加/删除新的订阅
但是无法收到订阅更新的消息
后台控制端未见报错消息
运行log如下（左侧为mirai，右侧为nonebot）：
![image](https://user-images.githubusercontent.com/37131177/135407057-119158ca-0380-406f-9945-36fd8f914ad6.png)

**Comment by Quan666** [comment]
放上推送消息时的日志
包括go-cqhttp、nonebot的

**Comment by fatinghenji** [comment]
没有看到任何推送相关日志

**Comment by Quan666** [comment]
那订阅有更新吗？不可能没有相关日志

**Comment by fatinghenji** [comment]
也没有看到关于订阅更新的日志行
所以才觉得很奇怪

**Comment by Quan666** [comment]
启动报错吗？用的是go-cqhttp吗？

**Comment by fatinghenji** [comment]
没有看到启动报错
使用的是[OneBot Mirai - CQHTTP Mirai](https://github.com/yyuueexxiinngg/onebot-kotlin)
补充启动log
![image](https://user-images.githubusercontent.com/37131177/135412725-1292a0ca-8f77-418a-b715-7fcfa856bf37.png)

**Comment by Quan666** [comment]
那可能是没有启动，可能是OneBot Mirai - CQHTTP Mirai缺少生命周期的接口，建议你使用go-cqhttp

**Comment by fatinghenji** [comment]
在刚刚部署的时候是可以成功接收和刷新rss的
后来就不行了，不清楚问题出在哪里

**Comment by Quan666** [comment]
在那之后你改了什么配置吗

**Comment by fatinghenji** [comment]
有增添其他插件，不知道是否有关
bot配置文件如下：
![image](https://user-images.githubusercontent.com/37131177/135414533-d2459f94-9793-41ab-ab2f-5538eccc89b5.png)
