### ISSUE TITLE
私聊推送正常，但是不会往群里推送消息

### ISSUE THREAD

**Issue by BestRailgun** [Quan666/ELF_RSS#201]
我是将本项目作为插件外挂在其他nonebot机器人下的，看日志是只发送给了好友，完全没有发到群里。在群里使用show命令可以正确显示订阅链接，有点百思不得其解...
![20211002205409](https://user-images.githubusercontent.com/53421615/135717441-8ae4e75e-814e-49f7-a56d-a1a2510e0da5.png)
![Inked20211002205432_LI](https://user-images.githubusercontent.com/53421615/135717443-55611110-5f6d-43b5-9506-51b78073b1c9.jpg)

**Comment by Quan666** [comment]
你设置了推送的群吗？
gocq的日志呢？

**Comment by BestRailgun** [comment]
同时设置了群和私聊，gocq的日志只显示发送给了私聊。
![3](https://user-images.githubusercontent.com/53421615/135719358-d7381001-a4e1-4f8e-8d32-3556703d2089.jpg)


私聊可以正确返回订阅信息
![1](https://user-images.githubusercontent.com/53421615/135719187-13aef59b-e292-4abf-961b-03a51f5368b9.jpg)

我在群内艾特bot也可以正确返回订阅
![2](https://user-images.githubusercontent.com/53421615/135719189-55083ac8-484e-4e73-80c9-0e85a3031e89.jpg)

检查了下群号应该没有问题

**Comment by Quan666** [comment]
有没有可能是风控

**Comment by BestRailgun** [comment]
我尝试直接在群组内订阅就能正常推送了，感谢作者。
