### ISSUE TITLE
更新报错 AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by meng-luo** [Quan666/ELF_RSS#207]
在jcgx检查更新后报错 

AttributeError: 'NoneType' object has no attribute 'group'

![Snipaste_2021-10-24_12-41-59](https://user-images.githubusercontent.com/79274361/138581137-4175667e-0d50-405e-b37c-76704ecee22a.png)

![Snipaste_2021-10-24_12-40-11](https://user-images.githubusercontent.com/79274361/138581102-7cba5bde-02c5-4055-8514-13dd824384c2.png)

**Comment by Quan666** [comment]
能提供下rss订阅链接吗？
以及复现步骤

**Comment by meng-luo** [comment]
链接bilibili/user/dynamic/928123/:disableEmbed?
私聊可以正常推送，群组却不行

**Comment by Quan666** [comment]
> 链接bilibili/user/dynamic/928123/:disableEmbed? 私聊可以正常推送，群组却不行

上面的日志截图是这个问题的吗？按理说私聊能发群聊不能发一般都是账号被风控了

**Comment by NekoAria** [comment]
> > 链接bilibili/user/dynamic/928123/:disableEmbed? 私聊可以正常推送，群组却不行
> 
> 上面的日志截图是这个问题的吗？按理说私聊能发群聊不能发一般都是账号被风控了

那个问题日志是处理无序列表的时候报错，应该不是一个问题。
