### ISSUE TITLE
rsshub订阅地址空着的时候无法启动

### ISSUE THREAD

**Issue by aharry-1** [Quan666/ELF_RSS#222]
![image](https://user-images.githubusercontent.com/43522771/140634428-51a29e47-6cc0-47cb-88f7-4a62eafc3444.png)
正常来说是这样的
如果把这一行留空，他就会报错
![image](https://user-images.githubusercontent.com/43522771/140634439-ae0063cb-3c2c-4650-ba2d-b18dd10cd1b5.png)
![image](https://user-images.githubusercontent.com/43522771/140634457-4084d701-6eb1-45f0-b336-98e42e5b333c.png)

**Comment by aharry-1** [comment]
旧版本好像是可以留空的
或者是我设置有问题？

**Comment by Quan666** [comment]
你可以选择默认的配置，而不是留空
不用rsshub填了也没啥影响

**Comment by aharry-1** [comment]
![image](https://user-images.githubusercontent.com/43522771/140634713-62707d70-685d-4b90-b603-e3b3ae4d3d2c.png)
我之前用旧版本的时候链接都是完整的，看来只能改一下了？

**Comment by aharry-1** [comment]
还是说其实是不影响推送的？

**Comment by NekoAria** [comment]
你如果要用像是 `weibo/rss/123456` 这样的简略地址来添加订阅，就不能空。
你不用也不需要特意去设置为空，因为加载配置的时候会检查配置是不是符合要求的地址格式。
就算是老版本也不允许改为空的。
你要是真看不顺眼直接删掉这行。

**Comment by aharry-1** [comment]
哦哦哦 谢谢大佬的解答
