### ISSUE TITLE
翻译失败问题

### ISSUE THREAD

**Issue by SakuraAzusa** [Quan666/ELF_RSS#248]
1. Bug 描述
启用翻译tl=1，订阅参数添加routeParams=exclude_rts_replies&readable=1，推特推送提示翻译失败Extra data: line 1 column 1200 (char 1199)
改为使用百度API并根据配置填入appid和secretKey，推送提示翻译失败'trans_result'
正常来说使用百度翻译api应该是API Key与Secret Key？尝试这样填入得到结果是相同的，服务器在香港应该也不存在连接问题

2. 截图、日志、配置、地址（issue 内上传图片或文件可直接粘贴）
启用tl=1
【Twitter @BP_Lord@SoulworkerKR】更新了!
----------------------
KOF15 예약해둬야겠다...
스트리머들 얼리액세스로 하는 거 보니까 재밌네 ㅋㅋ
翻译失败！Extra data: line 1 column 1091 (char 1090)

链接：https://twitter.com/soulumsword_kim/status/1492461911472230401
日期：2022年02月12日 19:33:42

启用百度api
【Twitter @BP_Lord@SoulworkerKR】更新了!
----------------------
Re @PagePyralis Exactly, she is VTuber and Arcadia Realm City Hall's official ambassador.
翻译(BaiduAPI)：
翻译失败：'trans_result'
链接：https://twitter.com/soulumsword_kim/status/1493784078453456899
日期：2022年02月16日 11:07:32
日志log：
[32m02-12 19:37:10[0m [[1mINFO[0m] [36m[4mELF_RSS2[0m[36m[0m | swkr 检查更新
[32m02-12 19:37:14[0m [[1mINFO[0m] [36m[4mELF_RSS2[0m[36m[0m | swkr 新消息推送完毕，共计：1

[32m02-16 11:08:57[0m [[1mINFO[0m] [36m[4msrc[0m[36m[0m | swkr 检查更新
[32m02-16 11:08:58[0m [[31m[1mERROR[0m] [36m[4msrc[0m[36m[0m | 'trans_result'
[32m02-16 11:08:59[0m [[31m[1mERROR[0m] [36m[4msrc[0m[36m[0m | 'trans_result'
[32m02-16 11:09:00[0m [[1mINFO[0m] [36m[4msrc[0m[36m[0m | swkr 新消息推送完毕，共计：1

3. 运行环境
    - 系统Ubuntu 20.04.1 LTS
    - python 3.8
    - go-cqhttp v1.0.0-rc1
    - ELF_RSS 版本v2.5.0

订阅地址：https://rss.shab.fun/twitter/user/soulumsword_kim/routeParams=exclude_rts_replies&readable=1

**Comment by Quan666** [comment]
最近比较忙，可能得周末修了。。

**Comment by NekoAria** [comment]
刚发布的 v2.5.2 里包含对翻译库的更换，你更新后再试试？
需要更新项目依赖。

**Comment by NekoAria** [comment]
刚发布的 v2.5.2 里包含对翻译库的更换，你更新后再试试？
需要更新项目依赖。

**Comment by NekoAria** [comment]
刚发布的 `v2.5.2` 里包含对翻译库的更换，你更新后再试试？
需要更新项目依赖。

**Comment by SakuraAzusa** [comment]
> 刚发布的 `v2.5.2` 里包含对翻译库的更换，你更新后再试试？ 需要更新项目依赖。

更新后使用翻译告诉我可用次数用完了，我不清楚是否能用了或者明天再试试？
```
【Twitter @BP_Lord@SoulWorkerKR】更新了!
----------------------
RT Ryri 🌡️️
Happy Birthday to 'the actual cat'
#소울워커 #SoulWorker #ソウルワーカー_FA
翻译：
MYMEMORY WARNING: YOU USED ALL AVAILABLE FREE TRANSLATIONS FOR TODAY. NEXT AVAILABLE IN  16 HOURS 42 MINUTES 54 SECONDS VISIT HTTPS://MYMEMORY.TRANSLATED.NET/DOC/USAGELIMITS.PHP TO TRANSLATE MORE 
链接：https://twitter.com/honeypeach29/status/1498687624776540177
日期：2022年03月01日 23:52:28
```

**Comment by Quan666** [comment]
> > 刚发布的 `v2.5.2` 里包含对翻译库的更换，你更新后再试试？ 需要更新项目依赖。
> 
> 更新后使用翻译告诉我可用次数用完了，我不清楚是否能用了或者明天再试试？
> ```
> 【Twitter @BP_Lord@SoulWorkerKR】更新了!
> ----------------------
> RT Ryri 🌡️️
> Happy Birthday to 'the actual cat'
> #소울워커 #SoulWorker #ソウルワーカー_FA
> 翻译：
> MYMEMORY WARNING: YOU USED ALL AVAILABLE FREE TRANSLATIONS FOR TODAY. NEXT AVAILABLE IN  16 HOURS 42 MINUTES 54 SECONDS VISIT HTTPS://MYMEMORY.TRANSLATED.NET/DOC/USAGELIMITS.PHP TO TRANSLATE MORE 
> 链接：https://twitter.com/honeypeach29/status/1498687624776540177
> 日期：2022年03月01日 23:52:28
> ```

这个库不太行，我看看能不能找个其他的

**Comment by NekoAria** [comment]
试试这个？：[
deep-translator](https://github.com/nidhaloff/deep-translator)

**Comment by Quan666** [comment]
> 试试这个？：[
> deep-translator](https://github.com/nidhaloff/deep-translator)

可

**Comment by Quan666** [comment]
@SakuraAzusa  https://github.com/Quan666/ELF_RSS/tree/%23248 试试这个分支的翻译，看行不行

**Comment by SakuraAzusa** [comment]
> @SakuraAzusa https://github.com/Quan666/ELF_RSS/tree/%23248 试试这个分支的翻译，看行不行

```
【Twitter @BP_Lord@SoulWorkerKR】更新了!
----------------------
#ソウルワーカー KR
「SOUL INVERSE」でのイラストはLive2Dみたいにアニメーションも適用されるそうです
翻译失败！HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=zh-CN&sl=auto&q=%5C%23%E3%82%BD%E3%82%A6%E3%83%AB%E3%83%AF%E3%83%BC%E3%82%AB%E3%83%BC%5C+KR%5C%0A%E3%80%8CSOUL%5C+INVERSE%E3%80%8D%E3%81%A7%E3%81%AE%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88%E3%81%AFLive2D%E3%81%BF%E3%81%9F%E3%81%84%E3%81%AB%E3%82%A2%E3%83%8B%E3%83%A1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%82%E9%81%A9%E7%94%A8%E3%81%95%E3%82%8C%E3%82%8B%E3%81%9D%E3%81%86%E3%81%A7%E3%81%99 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdc68440c40>: Failed to establish a new connection: [Errno 111] Connection refused')))

视频预览： 
链接：https://twitter.com/soulumsword_kim/status/1500076280221691906
日期：2022年03月05日 19:50:29
```
好像还是不行，连接被拒

**Comment by Quan666** [comment]
> > @SakuraAzusa https://github.com/Quan666/ELF_RSS/tree/%23248 试试这个分支的翻译，看行不行
> 
> ```
> 【Twitter @BP_Lord@SoulWorkerKR】更新了!
> ----------------------
> #ソウルワーカー KR
> 「SOUL INVERSE」でのイラストはLive2Dみたいにアニメーションも適用されるそうです
> 翻译失败！HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=zh-CN&sl=auto&q=%5C%23%E3%82%BD%E3%82%A6%E3%83%AB%E3%83%AF%E3%83%BC%E3%82%AB%E3%83%BC%5C+KR%5C%0A%E3%80%8CSOUL%5C+INVERSE%E3%80%8D%E3%81%A7%E3%81%AE%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88%E3%81%AFLive2D%E3%81%BF%E3%81%9F%E3%81%84%E3%81%AB%E3%82%A2%E3%83%8B%E3%83%A1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%82%E9%81%A9%E7%94%A8%E3%81%95%E3%82%8C%E3%82%8B%E3%81%9D%E3%81%86%E3%81%A7%E3%81%99 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdc68440c40>: Failed to establish a new connection: [Errno 111] Connection refused')))
> 
> 视频预览： 
> 链接：https://twitter.com/soulumsword_kim/status/1500076280221691906
> 日期：2022年03月05日 19:50:29
> ```
> 好像还是不行，连接被拒

要配置代理的

**Comment by SakuraAzusa** [comment]
啊这，需要配置代理使用的吗，因为机子在香港就是为了免去代理的步骤

**Comment by NekoAria** [comment]
https://github.com/Quan666/ELF_RSS/blob/376b93cadfc125b8ba1f11f520caf7a8de95c105/src/plugins/ELF_RSS2/RSS/routes/Parsing/handle_translation.py#L13-L16
这里写死了，应该写成：

```Python
proxies = (
    {
        "https": config.rss_proxy,
        "http": config.rss_proxy,
    }
    if config.rss_proxy
    else None
)
```

没配置代理的就不会走代理。

**Comment by Quan666** [comment]
啊，我去改改

**Comment by Quan666** [comment]
@SakuraAzusa 再试试

**Comment by SakuraAzusa** [comment]
刚使用的时候第一次是可以的,之后第二条推也是额度已满了,或者说可以看看把百度翻译的api对接好之类的?
`MYMEMORY WARNING: YOU USED ALL AVAILABLE FREE TRANSLATIONS FOR TODAY. NEXT AVAILABLE IN  22 HOURS 56 MINUTES 36 SECONDS VISIT HTTPS://MYMEMORY.TRANSLATED.NET/DOC/USAGELIMITS.PHP TO TRANSLATE MORE`

**Comment by NekoAria** [comment]
> 刚使用的时候第一次是可以的,之后第二条推也是额度已满了,或者说可以看看把百度翻译的api对接好之类的? `MYMEMORY WARNING: YOU USED ALL AVAILABLE FREE TRANSLATIONS FOR TODAY. NEXT AVAILABLE IN 22 HOURS 56 MINUTES 36 SECONDS VISIT HTTPS://MYMEMORY.TRANSLATED.NET/DOC/USAGELIMITS.PHP TO TRANSLATE MORE`

你这结果也不是 Google 翻译啊？
怎么又变成之前的 MYMEMORY 了？

**Comment by Quan666** [comment]
是这个分支 https://github.com/Quan666/ELF_RSS/tree/%23248
@SakuraAzusa

**Comment by SakuraAzusa** [comment]
昨天处理的时候启动错了，这次clone了项目启动同样是443的错误，分片发送导致消息全部错乱了放截图吧
![pic](https://user-images.githubusercontent.com/97999241/157146295-2eb2d5a4-2aea-4165-a7b9-c945d760847a.jpg)
然后我也尝试了服务器ping谷歌是正常的
![pic2](https://user-images.githubusercontent.com/97999241/157146346-a13a1f43-567a-4a7e-a054-3f4cdf7e2df8.png)
![pic3](https://user-images.githubusercontent.com/97999241/157146354-4d227fc5-8c3d-48d8-9520-267ce7c524f5.png)

**Comment by Quan666** [comment]
你配置文件里面rss_proxy的值有设置吗？设置了的话，删除试试

**Comment by SakuraAzusa** [comment]
留空后翻译正常了，感谢
配置文件都是默认的没有修改，可能之后要做一下留空处理
