### ISSUE TITLE
推送异常无限循环推送

### ISSUE THREAD

**Issue by SakuraAzusa** [Quan666/ELF_RSS#253]
又来给你送bug了，现在重启删除订阅并重新订阅后无异常，但是官方发博频率很低情况未知
1. Bug 描述
> 不确定是否为问题关键，先描述过程
服务器19号重装并重新部署停止一天，备份.env.dev与data文件夹，启动后其他订阅正常补充推送，arkn无反应
今日11点更新微博，会产生每5分钟最近4条微博循环推送
后检查log发现每次检查arkn更新都会产生触发器异常
示例：
```Python
02-19 20:21:25 [ERROR] apscheduler | Job "check_update (trigger: interval[0:05:00], next run at: 2022-02-19 20:26:32 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
```
2. 截图、日志、配置、地址（issue 内上传图片或文件可直接粘贴）
```Python
02-22 11:03:15 [INFO] src | arkn 检查更新
02-22 11:03:24 [INFO] src | yxdl 检查更新
02-22 11:03:26 [INFO] src | yxdl 没有新信息
02-22 11:03:32 [INFO] src | swkr 检查更新
02-22 11:03:32 [INFO] src | swkr 没有新信息
02-22 11:03:36 [ERROR] src | E: <ActionFailed data=None, echo={'seq': 262}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出> 链接：[https://weibo.com/6279793937/Lg1bUuLlH]
02-22 11:03:42 [ERROR] src | E: <ActionFailed data=None, echo={'seq': 263}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出> 链接：[https://weibo.com/6279793937/Lg1bUuLlH]
02-22 11:04:45 [ERROR] apscheduler | Job "check_update (trigger: interval[0:05:00], next run at: 2022-02-22 11:08:19 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 232, in run
    uvicorn.run(
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.8/dist-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/root/ELF/ELF/./src/plugins/ELF_RSS2/RSS/util.py", line 13, in wrapper
    return await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/root/ELF/ELF/./src/plugins/ELF_RSS2/RSS/my_trigger.py", line 16, in check_update
    await rss_parsing.start(rss)
  File "/root/ELF/ELF/./src/plugins/ELF_RSS2/RSS/rss_parsing.py", line 69, in start
    await pr.start(rss_name=rss.name, new_rss=new_rss)
  File "/root/ELF/ELF/./src/plugins/ELF_RSS2/RSS/routes/Parsing/__init__.py", line 218, in start
    tmp = await handler.func(
  File "/root/ELF/ELF/./src/plugins/ELF_RSS2/RSS/routes/weibo.py", line 19, in handle_summary
    tmp += await handle_html_tag(html=summary_html)
  File "/root/ELF/ELF/./src/plugins/ELF_RSS2/RSS/routes/Parsing/handle_html_tag.py", line 76, in handle_html_tag
    a_str = re.search(r"<a.+?</a>", html_unescape(str(a)), flags=re.DOTALL)[0]
TypeError: 'NoneType' object is not subscriptable
02-22 11:08:13 [SUCCESS] nonebot | ONEBOT V11 1454042719 | [notice.group_recall]: {'time': 16****86, 'self_id': 14****19, 'post_type': 'notice', 'notice_type': 'group_recall', 'user_id': 25****12, 'group_id': 90****11, 'operator_id': 25****12, 'message_id': 19****23}
02-22 11:08:19 [INFO] src | arkn 检查更新
02-22 11:08:26 [INFO] src | yxdl 检查更新
02-22 11:08:33 [INFO] src | yxdl 新消息推送完毕，共计：1
02-22 11:08:41 [ERROR] src | E: <ActionFailed data=None, echo={'seq': 279}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出> 链接：[https://weibo.com/6279793937/Lg1bUuLlH]
02-22 11:08:47 [ERROR] src | E: <ActionFailed data=None, echo={'seq': 280}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出> 链接：[https://weibo.com/6279793937/Lg1bUuLlH]
02-22 11:09:45 [ERROR] apscheduler | Job "check_update (trigger: interval[0:05:00], next run at: 2022-02-22 11:13:22 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 232, in run
    uvicorn.run(
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.8/dist-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/root/ELF/ELF/./src/plugins/ELF_RSS2/RSS/util.py", line 13, in wrapper
    return await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/root/ELF/ELF/./src/plugins/ELF_RSS2/RSS/my_trigger.py", line 16, in check_update
    await rss_parsing.start(rss)
  File "/root/ELF/ELF/./src/plugins/ELF_RSS2/RSS/rss_parsing.py", line 69, in start
    await pr.start(rss_name=rss.name, new_rss=new_rss)
  File "/root/ELF/ELF/./src/plugins/ELF_RSS2/RSS/routes/Parsing/__init__.py", line 218, in start
    tmp = await handler.func(
  File "/root/ELF/ELF/./src/plugins/ELF_RSS2/RSS/routes/weibo.py", line 19, in handle_summary
    tmp += await handle_html_tag(html=summary_html)
  File "/root/ELF/ELF/./src/plugins/ELF_RSS2/RSS/routes/Parsing/handle_html_tag.py", line 76, in handle_html_tag
    a_str = re.search(r"<a.+?</a>", html_unescape(str(a)), flags=re.DOTALL)[0]
TypeError: 'NoneType' object is not subscriptable
```

    - 出问题的订阅地址
    - https://rss.shab.fun/weibo/user/6279793937/readable=1&showRetweetTextInTitle=0
3. 运行环境
    - 系统Ubuntu 20.04.1 LTS
    - python 3.8
    - go-cqhttp v1.0.0-rc1
    - ELF_RSS 版本v2.5.0

**Comment by NekoAria** [comment]
这满屏乱码让人看得直泛恶心。。。
还好我知道这是ANSI格式，转换了下。

**Comment by NekoAria** [comment]
初步判断应该是内容过长导致发送失败，后续该考虑发送失败的时候自动尝试发送截断部分内容再发送。

**Comment by NekoAria** [comment]
另一个错误是遇到的 `a` 标签里刚好没内容，正则逻辑不完备导致没获取到。

**Comment by NekoAria** [comment]
不过从我的测试结果来看，似乎还没达到消息过长无法发送的地步。
不知道是否和我的 gocq 配置有关，我开启了强制分片：`force-fragment: true`
你如果开启了这个配置，再去data目录下修改 `arkn.json` ，删掉带 `https://weibo.com/6279793937/Lg1bUuLlH` 这个链接的部分，格式如：

```JSON
"6": {
    "hash": "cd1157bac10947d64888f0b68ef674b7",
    "id": "https://weibo.com/6279793937/Lg1bUuLlH",
    "link": "https://weibo.com/6279793937/Lg1bUuLlH",
    "published": "Fri, 18 Feb 2022 03:00:02 GMT",
    "title": "#明日方舟#危机合约「寻昼行动」即将开启一、危机合约，第8赛季「寻昼行动」开启赛季开启时间：02月24日 16:00 - 03月10日 03:59危机合约解锁条件：通关主线 2-1..."
}
```

如果用 vi ，输入 `/Lg1bUuLlH` 后回车，光标移动到索引那行，然后直接 `7dd` 就能删除了。
`:wq` 保存后再等待机器人抓取结果。为了尽快看到测试结果，可以先把抓取频率改为 1 分钟。

**Comment by SakuraAzusa** [comment]
> 不过从我的测试结果来看，似乎还没达到消息过长无法发送的地步。 不知道是否和我的 gocq 配置有关，我开启了强制分片：`force-fragment: true` 你如果开启了这个配置，再去data目录下修改 `arkn.json` ，删掉带 `https://weibo.com/6279793937/Lg1bUuLlH` 这个链接的部分，格式如：
> 
> ```json
> "6": {
>     "hash": "cd1157bac10947d64888f0b68ef674b7",
>     "id": "https://weibo.com/6279793937/Lg1bUuLlH",
>     "link": "https://weibo.com/6279793937/Lg1bUuLlH",
>     "published": "Fri, 18 Feb 2022 03:00:02 GMT",
>     "title": "#明日方舟#危机合约「寻昼行动」即将开启一、危机合约，第8赛季「寻昼行动」开启赛季开启时间：02月24日 16:00 - 03月10日 03:59危机合约解锁条件：通关主线 2-1..."
> }
> ```
> 
> 如果用 vi ，输入 `/Lg1bUuLlH` 后回车，光标移动到索引那行，然后直接 `7dd` 就能删除了。 `:wq` 保存后再等待机器人抓取结果。为了尽快看到测试结果，可以先把抓取频率改为 1 分钟。

开启强制分片后log如下：
```
[32m02-23 09:08:41[0m [[1mINFO[0m] [36m[4msrc[0m[36m[0m | arkn 检查更新
[32m02-23 09:08:51[0m [[31m[1mERROR[0m] [36m[4msrc[0m[36m[0m | E: <ActionFailed data=None, echo={'seq': 3}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出> 链接：[https://weibo.com/6279793937/Lg1bUuLlH]
[32m02-23 09:08:57[0m [[31m[1mERROR[0m] [36m[4msrc[0m[36m[0m | E: <ActionFailed data=None, echo={'seq': 4}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出> 链接：[https://weibo.com/6279793937/Lg1bUuLlH]
[32m02-23 09:08:57[0m [[1mINFO[0m] [36m[4msrc[0m[36m[0m | arkn 没有新信息
```

消息没有被推送，消息过长应该不会，我尝试过使用gocq推送超长信息没有问题
还有一点是如果微博附带视频，推送时会将下面url推送出来，是否会导致内容过多问题，能否像推特一样截取部分视频gif或只推送链接，能同时推送视频就更好了
带视频内容举例：
```
【游戏动力的微博】更新了!
----------------------
反乌托邦游戏《旁观者3》已在Steam提供免费试玩版，正式版将于 3 月 4 日发售，登陆PC平台，支持中文。玩家扮演的角色曾经拥有一份舒适的工作，但因为陷害很可能失去现在所拥有的一切。为了防止这一切发生，你不得不与一位高级安全官员做了交易。伪装成房东，闯入租户的公寓，搜索非法物品，回到部里，对同事和上级进行间谍和阴谋活动。  游戏动力的微博视频: https://video.weibo.com/show?fid=1034:4739817939075170

<source src="https://f.video.weibocdn.com/o0/lhkjn4m3lx07TY0K53sc0104120076dI0E010.mp4?label=mp4_ld&template=640x360.25.0&ori=0&ps=1CwnkDw1GXwCQx&Expires=1645580152&ssig=9K89vivknt&KID=unistore,video"/>视频无法显示，请前往 微博视频: https://video.weibo.com/show?fid=1034%3A4739817939075170&luicode=10000011&lfid=2304135762457113
观看。 [图片]
视频封面： [图片]
链接：https://weibo.com/5762457113/LgLlwogwN
日期：2022年02月23日 08:30:04
```

**Comment by SakuraAzusa** [comment]
看了下gocq那边，昨天推送大量超长消息被风控了，可能要推迟测试

**Comment by SakuraAzusa** [comment]
尝试改成推送为个人，消息正常推送但实际无内容发出，同时尝试命令change也无反应了(log正常)
但是发送图片和一些带图文的推特和短微博又是正常的，迷惑起来了

**Comment by NekoAria** [comment]
> > 不过从我的测试结果来看，似乎还没达到消息过长无法发送的地步。 不知道是否和我的 gocq 配置有关，我开启了强制分片：`force-fragment: true` 你如果开启了这个配置，再去data目录下修改 `arkn.json` ，删掉带 `https://weibo.com/6279793937/Lg1bUuLlH` 这个链接的部分，格式如：
> > ```json
> > "6": {
> >     "hash": "cd1157bac10947d64888f0b68ef674b7",
> >     "id": "https://weibo.com/6279793937/Lg1bUuLlH",
> >     "link": "https://weibo.com/6279793937/Lg1bUuLlH",
> >     "published": "Fri, 18 Feb 2022 03:00:02 GMT",
> >     "title": "#明日方舟#危机合约「寻昼行动」即将开启一、危机合约，第8赛季「寻昼行动」开启赛季开启时间：02月24日 16:00 - 03月10日 03:59危机合约解锁条件：通关主线 2-1..."
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果用 vi ，输入 `/Lg1bUuLlH` 后回车，光标移动到索引那行，然后直接 `7dd` 就能删除了。 `:wq` 保存后再等待机器人抓取结果。为了尽快看到测试结果，可以先把抓取频率改为 1 分钟。
> 
> 开启强制分片后log如下：
> 
> ```
> �[32m02-23 09:08:41�[0m [�[1mINFO�[0m] �[36m�[4msrc�[0m�[36m�[0m | arkn 检查更新
> �[32m02-23 09:08:51�[0m [�[31m�[1mERROR�[0m] �[36m�[4msrc�[0m�[36m�[0m | E: <ActionFailed data=None, echo={'seq': 3}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出> 链接：[https://weibo.com/6279793937/Lg1bUuLlH]
> �[32m02-23 09:08:57�[0m [�[31m�[1mERROR�[0m] �[36m�[4msrc�[0m�[36m�[0m | E: <ActionFailed data=None, echo={'seq': 4}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出> 链接：[https://weibo.com/6279793937/Lg1bUuLlH]
> �[32m02-23 09:08:57�[0m [�[1mINFO�[0m] �[36m�[4msrc�[0m�[36m�[0m | arkn 没有新信息
> ```
> 
> 消息没有被推送，消息过长应该不会，我尝试过使用gocq推送超长信息没有问题 还有一点是如果微博附带视频，推送时会将下面url推送出来，是否会导致内容过多问题，能否像推特一样截取部分视频gif或只推送链接，能同时推送视频就更好了 带视频内容举例：
> 
> ```
> 【游戏动力的微博】更新了!
> ----------------------
> 反乌托邦游戏《旁观者3》已在Steam提供免费试玩版，正式版将于 3 月 4 日发售，登陆PC平台，支持中文。玩家扮演的角色曾经拥有一份舒适的工作，但因为陷害很可能失去现在所拥有的一切。为了防止这一切发生，你不得不与一位高级安全官员做了交易。伪装成房东，闯入租户的公寓，搜索非法物品，回到部里，对同事和上级进行间谍和阴谋活动。  游戏动力的微博视频: https://video.weibo.com/show?fid=1034:4739817939075170
> 
> <source src="https://f.video.weibocdn.com/o0/lhkjn4m3lx07TY0K53sc0104120076dI0E010.mp4?label=mp4_ld&template=640x360.25.0&ori=0&ps=1CwnkDw1GXwCQx&Expires=1645580152&ssig=9K89vivknt&KID=unistore,video"/>视频无法显示，请前往 微博视频: https://video.weibo.com/show?fid=1034%3A4739817939075170&luicode=10000011&lfid=2304135762457113
> 观看。 [图片]
> 视频封面： [图片]
> 链接：https://weibo.com/5762457113/LgLlwogwN
> 日期：2022年02月23日 08:30:04
> ```

那还是对 `video` 标签的正则处理逻辑不完备，导致没把这部分内容处理掉。
至于像推特那样做动图预览比较麻烦，虽然这 `source` 的 `src` 属性就是视频地址，但是这个地址里的 `Expires` 和 `ssig` 字段都是会变动的。
只有找个那种在线获取微博视频的网站，封装成函数调用才可行。但是这就比推特那个多了一步。（其实推特那个我也是突发奇想的，虽然弄了我后来也没订阅推特了

（本来想引用回复的，点到编辑了。。。

**Comment by NekoAria** [comment]
> 尝试改成推送为个人，消息正常推送但实际无内容发出，同时尝试命令change也无反应了(log正常) 但是发送图片和一些带图文的推特和短微博又是正常的，迷惑起来了

我昨天也遇到这个情况了，不知道是否是因为触发了风控机制。

**Comment by NekoAria** [comment]
刚发布了 v2.5.1 ，你更新后再测试看看。
没什么问题就关闭这个 issue 了。

**Comment by SakuraAzusa** [comment]
更新后推送正常了，感谢
但是丢失了最后的部分内容，可能是分段发送导致？
推送：
```
关卡说明：新增剿灭委托关卡【小丘郡郊野】将替换现有剿灭委托关卡【南方监狱】，现剿灭委托关卡【南方监狱】将在关闭后收录进假定作战目标

更多活动内容请...[图片]
视频封面：[图片]
链接：https://weibo.com/6279793937/Lg1bUuLlH
日期：2022年02月18日 11:00:02
```
原文：
```
关卡说明：新增剿灭委托关卡【小丘郡郊野】将替换现有剿灭委托关卡【南方监狱】，现剿灭委托关卡【南方监狱】将在关闭后收录进假定作战目标

更多活动内容请持续关注《明日方舟》游戏内公告、官网、官方微博及微信公众号。 明日方舟Arknights的微...
```

**Comment by NekoAria** [comment]
> 更新后推送正常了，感谢 但是丢失了最后的部分内容，可能是分段发送导致？ 推送：
> 
> ```
> 关卡说明：新增剿灭委托关卡【小丘郡郊野】将替换现有剿灭委托关卡【南方监狱】，现剿灭委托关卡【南方监狱】将在关闭后收录进假定作战目标
> 
> 更多活动内容请...[图片]
> 视频封面：[图片]
> 链接：https://weibo.com/6279793937/Lg1bUuLlH
> 日期：2022年02月18日 11:00:02
> ```
> 
> 原文：
> 
> ```
> 关卡说明：新增剿灭委托关卡【小丘郡郊野】将替换现有剿灭委托关卡【南方监狱】，现剿灭委托关卡【南方监狱】将在关闭后收录进假定作战目标
> 
> 更多活动内容请持续关注《明日方舟》游戏内公告、官网、官方微博及微信公众号。 明日方舟Arknights的微...
> ```

出于“防止消息太长刷屏，以及消息过长发送失败的情况”的考虑，现在配置项正文长度限制 `max_length` 的默认值是 1024 。
你如果想改，可以往 `.env.prod` 里添加如 `MAX_LENGTH=2048` ，而这个值如果是 0 就无限制，但是不建议这样，因为容易消息过长发送失败然后触发风控。

**Comment by SakuraAzusa** [comment]
> > 更新后推送正常了，感谢 但是丢失了最后的部分内容，可能是分段发送导致？ 推送：
> > ```
> > 关卡说明：新增剿灭委托关卡【小丘郡郊野】将替换现有剿灭委托关卡【南方监狱】，现剿灭委托关卡【南方监狱】将在关闭后收录进假定作战目标
> > 
> > 更多活动内容请...[图片]
> > 视频封面：[图片]
> > 链接：https://weibo.com/6279793937/Lg1bUuLlH
> > 日期：2022年02月18日 11:00:02
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 原文：
> > ```
> > 关卡说明：新增剿灭委托关卡【小丘郡郊野】将替换现有剿灭委托关卡【南方监狱】，现剿灭委托关卡【南方监狱】将在关闭后收录进假定作战目标
> > 
> > 更多活动内容请持续关注《明日方舟》游戏内公告、官网、官方微博及微信公众号。 明日方舟Arknights的微...
> > ```
> 
> 出于“防止消息太长刷屏，以及消息过长发送失败的情况”的考虑，现在配置项正文长度限制 `max_length` 的默认值是 1024 。 你如果想改，可以往 `.env.prod` 里添加如 `MAX_LENGTH=2048` ，而这个值如果是 0 就无限制，但是不建议这样，因为容易消息过长发送失败然后触发风控。

了解了
