### ISSUE TITLE
特定rss下无限循环推送已经推送过的消息

### ISSUE THREAD

**Issue by TeoZler** [Quan666/ELF_RSS#255]
1. Bug 描述

- 可以稳定复现，步骤：推送/nhentai/search/:keyword/:mode?这个路由相关的链接

- 期望的正常行为是怎么样的：不推送已经推送过的内容

2. 截图、日志、配置、地址

- 问题日志：

> 02-24 13:57:24 [INFO] src | 定时任务 nh 添加成功
02-24 13:57:24 [INFO] src | ELF_RSS 订阅器启动成功！
02-24 13:57:24 [INFO] nonebot | Matcher <Matcher from src.plugins.ELF_RSS2.start, type=meta_event, priority=1, temp=False> running complete
02-24 13:58:29 [INFO] src | nh 检查更新
02-24 13:59:36 [WARNING] apscheduler | Execution of job "check_update (trigger: interval[0:01:00], next run at: 2022-02-24 13:59:36 CST)" skipped: maximum number of running instances reached (1)
02-24 14:00:08 [INFO] src | nh 新消息推送完毕，共计：24
02-24 14:00:40 [INFO] src | nh 检查更新
02-24 14:00:40 [INFO] src | nh 没有新信息
02-24 14:01:48 [INFO] src | nh 检查更新
02-24 14:01:48 [INFO] src | nh 没有新信息
02-24 14:02:57 [INFO] src | nh 检查更新
02-24 14:02:57 [INFO] src | nh 没有新信息
02-24 14:04:01 [INFO] src | nh 检查更新
02-24 14:05:04 [WARNING] apscheduler | Execution of job "check_update (trigger: interval[0:01:00], next run at: 2022-02-24 14:05:04 CST)" skipped: maximum number of running instances reached (1)
02-24 14:05:33 [INFO] src | nh 新消息推送完毕，共计：24
02-24 14:06:09 [INFO] src | nh 检查更新
02-24 14:06:09 [INFO] src | nh 没有新信息
02-24 14:07:12 [INFO] src | nh 检查更新
02-24 14:07:12 [INFO] src | nh 没有新信息
02-24 14:08:21 [INFO] src | nh 检查更新
02-24 14:08:21 [INFO] src | nh 没有新信息
02-24 14:09:31 [INFO] src | nh 检查更新
02-24 14:10:40 [WARNING] apscheduler | Execution of job "check_update (trigger: interval[0:01:00], next run at: 2022-02-24 14:10:39 CST)" skipped: maximum number of running instances reached (1)
02-24 14:11:13 [INFO] src | nh 新消息推送完毕，共计：24

- 出问题的订阅地址：https://rss.wen-he.icu/nhentai/search/Chinese/simple   |   https://rss.wen-he.icu/nhentai/search/lolicon+Chinese/simple   （我只测试了两个链接，猜测这个路由都会出现这个问题）

3. 运行环境

- windows10 1809

- python3.8.3

- go-cqhttp 1.0.0rc1

- ELF_RSS 2.5.1

**Comment by NekoAria** [comment]
是否配置了 `rsshub_backup` 配置项？
不同 rsshub 实例生成的结果有可能不同，包括消息内容和时间，导致 bot 判断成不同的消息。
可以用 change 指令启用 `mode=link` 去重模式。
