### ISSUE TITLE
短链无法访问

### ISSUE THREAD

**Issue by YipSzeho** [Quan666/ELF_RSS#26]
搭配cq-picsearcher-bot使用时，若SauceNAO搜图返回的链接是推特的，会被转换成短链，且短链无法访问，有没有办法不转换成短链
![Image](https://raw.githubusercontent.com/YipSzeho/gittalk/main/QQ%E6%88%AA%E5%9B%BE20201231124115.png)

**Comment by Quan666** [comment]
这个问题与本项目无关。请去 [cq-picsearcher-bot](https://github.com/Tsuk1ko/cq-picsearcher-bot) 提 issue
