### ISSUE TITLE
没有重试，直接报错已达最大重试次数

### ISSUE THREAD

**Issue by YipSzeho** [Quan666/ELF_RSS#266]
没有自动重试，而是直接报告已达最大重试次数

03-08 07:52:19 [INFO] src | p站日榜 检查更新
03-08 07:52:19 [INFO] src | 观网微博 检查更新
03-08 07:52:20 [INFO] src | 观网微博 没有新信息
03-08 07:52:23 [ERROR] src | p站日榜[https://rsshub.xxxxxx.xx/pixiv/ranking/day]抓取失败！已达最大重试次数！请检查
订阅地址！
03-08 07:52:24 [INFO] src | 测试 检查更新
03-08 07:52:28 [ERROR] src | 测试[https://rsshub.xxxxxx.xx/twitter/user/heripiro]抓取失败！已达最大重试次数！请检查订阅地址！

运行环境
    - Windows Server 2022 
    - python 版本 3.9.10
    - go-cqhttp 版本  v1.0.0-rc1
    - ELF_RSS 版本 v2.5.2

**Comment by NekoAria** [comment]
无法复现，不知道为什么。

**Comment by NekoAria** [comment]
点错了。。。

**Comment by NekoAria** [comment]
我的测试结果：
```Shell
6|elf_rss  | 03-08 15:30:28 [WARNING] src | test 抓取失败！将重试最多 5 次！
6|elf_rss  | 03-08 15:30:29 [WARNING] src | test 抓取失败！将重试最多 5 次！
6|elf_rss  | 03-08 15:30:31 [WARNING] src | test 抓取失败！将重试最多 5 次！
6|elf_rss  | 03-08 15:30:33 [WARNING] src | test 抓取失败！将重试最多 5 次！
6|elf_rss  | 03-08 15:30:34 [WARNING] src | test 抓取失败！将重试最多 5 次！
6|elf_rss  | 03-08 15:30:34 [ERROR] src | test[https://rsshub.xxxxxx.xx/pixiv/ranking/day]抓取失败！已达最大重试次数！ 请检查订阅地址！
```

**Comment by NekoAria** [comment]
你试试我新开的一个分支： https://github.com/NekoAria/ELF_RSS/tree/fix%23266

**Comment by YipSzeho** [comment]
更新版本已解决
