### ISSUE TITLE
已开ssr，但订阅rss依然无法推送

### ISSUE THREAD

**Issue by yoiyami96** [Quan666/ELF_RSS#277]
环境是win11，python3.10，ELF_RSS v2.5.6，go-cqhttp v1.0.0-rc1，rss链接为https://rss.shab.fun/twitter/likes/leere1030（感谢大佬自建的rsshub，已小捐一顿早饭钱）
已开ssr，能正常访问外网，env文件也填写了代理地址，但不管修改proxy为1还是0，bot依旧无法正常推送（很抱歉在这里提这种简单的问题，因为我不知道群号）
**当proxy为1时：**
04-20 21:55:44 [INFO] src | 推特 检查更新
04-20 21:55:48 [WARNING] src | 推特 抓取失败！已经尝试最多 6 次！
**当proxy为0时：**
04-20 21:49:09 [INFO] src | 推特 检查更新
04-20 21:49:31 [WARNING] src | 图片[https://pbs.twimg.com/media/FQvGSo5aMAEjidE?format=jpg&name=orig]下载失败！将重试最
多 5 次！
Cannot connect to host pbs.twimg.com:443 ssl:default [信号灯超时时间已到]
04-20 21:49:52 [WARNING] src | 图片[https://pbs.twimg.com/media/FQvGSo5aMAEjidE?format=jpg&name=orig]下载失败！将重试最
多 5 次！
Cannot connect to host pbs.twimg.com:443 ssl:default [信号灯超时时间已到]
04-20 21:49:52 [ERROR] src | 图片[https://pbs.twimg.com/media/FQvGSo5aMAEjidE?format=jpg&name=orig]下载失败！已达最大重 试次数！有可能需要开启代理！
04-20 21:49:52 [INFO] src | 推特 新消息推送完毕，共计：1

**Comment by NekoAria** [comment]
请问你填写的代理地址是这个格式的吗："127.0.0.1:7890"？
另外群号在 [README.md](https://github.com/Quan666/ELF_RSS#readme) 开头就有。

**Comment by yoiyami96** [comment]
> 请问你填写的代理地址是这个格式的吗："127.0.0.1:7890"？ 另外群号在 [README.md](https://github.com/Quan666/ELF_RSS#readme) 开头就有。

是的，我填的"127.0.0.1:1080"，端口没错，并且ssr开全局还是pac都没用

**Comment by Quan666** [comment]
超时，很有可能是代理问题，你排除一下是端口写错了还是代理端口没开启？

**Comment by yoiyami96** [comment]
> 超时，很有可能是代理问题，你排除一下是端口写错了还是代理端口没开启？

我一开始用的ssr，默认端口1080，后来又试了clash，默认端口7890，设置如图，都开的pac模式，应该没设置错吧，env里也是按"127.0.0.1:7890"格式填的
![](https://s3.bmp.ovh/imgs/2022/04/21/b44899cd56c6382d.png)
![](https://s3.bmp.ovh/imgs/2022/04/21/3cd45f25853883ad.png)

**Comment by Quan666** [comment]
clash开全局模式也不行吗？

**Comment by yoiyami96** [comment]
> clash开全局模式也不行吗？

不行，还是一样的问题，proxy为1时抓取失败，proxy为0时图片下载失败

**Comment by Quan666** [comment]
那你应该设置为proxy=1
你试试开全局浏览器访问rsshub试试

**Comment by yoiyami96** [comment]
> 那你应该设置为proxy=1 你试试开全局浏览器访问rsshub试试

开全局可以访问，rsshub.app和rss.shab.fun都可以
