### ISSUE TITLE
子频道内推送报错

### ISSUE THREAD

**Issue by BestRailgun** [Quan666/ELF_RSS#290]
环境:
- Ubuntu 20.04 LTS
- python v3.8
- go-cqhttp v1.0.0-rc1
- ELF_RSS v2.5.6

1. Bug 描述
    - 无法完成频道内子频道的推送
![屏幕截图 2022-04-29 211928](https://user-images.githubusercontent.com/53421615/165953073-8dd86aa4-a328-4dc2-b4ab-19b2997276fc.png)

回退至14天之前的release解决，但是直接git clone的版本会有此问题。
好像是字符串的问题？

**Comment by NekoAria** [comment]
应该是之前重构的时候没注意，写错了调用方法。
你试试这个分支：[fix#290](https://github.com/Quan666/ELF_RSS/tree/fix%23290)

**Comment by BestRailgun** [comment]
@NekoAria 谢谢大佬，测试过正常了。
