### ISSUE TITLE
单条消息发送间隔

### ISSUE THREAD

**Issue by Sora39831** [Quan666/ELF_RSS#292]
请说明：

1. 订阅消息发送间隔
2. 经常更新一次订阅就会发送大量消息，貌似一下子发送太多消息容易被风控，所以建议添加一个单条消息发送间隔的功能

**Comment by NekoAria** [comment]
这个逻辑实现是不难，但是设计上可能不合理。
首先，每个检查更新任务周期之间有 10 秒内的抖动，所以这本来就已经一定程度上减少了同时发送大量消息的概率；
其次，每个检查更新任务之间是独立的，所以如果只是简单在每个更新任务的周期内的消息增加间隔，并不能完全避免另一个检查更新任务在这时发送消息。

**Comment by NekoAria** [comment]
要做到全局每次发送消息之间都有间隔，只能加上一个锁，但是这样一来逻辑就变得复杂了。
另外还需要考虑的问题是，一个订阅如果不只是个人订阅，同时还有群组或者频道订阅的情况，该怎么设计这个间隔。

**Comment by NekoAria** [comment]
先简单地在发送消息之前加个锁，发了个分支，请你帮忙测试一下：[sending-lock](https://github.com/Quan666/ELF_RSS/tree/sending-lock)
如果效果（尤其是担心性能）不会太糟糕，就直接合并到主分支了。

**Comment by Sora39831** [comment]
好的麻烦你了，我试试看

**Comment by NekoAria** [comment]
另外开了个新的分支，请你帮忙测试一下：[v2.6.0](https://github.com/Quan666/ELF_RSS/tree/v2.6.0)
因为改了检查更新相关的逻辑，建议在最近一轮检查更新任务完成后停止机器人，删除缓存文件后再切换到这个分支。

**Comment by Quan666** [comment]
#295
