### ISSUE TITLE
推送已“过时”的消息

### ISSUE THREAD

**Issue by ddaodan** [Quan666/ELF_RSS#294]
1. Bug 描述
    - 现在是5月，但有时候会推送4月的信息
2. 截图、日志、配置、地址（issue 内上传图片或文件可直接粘贴）
    - ![Screenshot_2022-05-04-00-17-12-824_com tencent mobileqq](https://user-images.githubusercontent.com/40017293/166493532-61690e3e-5263-4f44-aace-650e1acf8a21.jpg)

    - 问题日志，因出现时间不固定无法查找
    - 出问题的订阅地址 https://rsshub-d.herokuapp.com/twitter/user/noriopro
3. 运行环境
    - 系统 Debian 4.19.0
    - python 版本 3.10.0
    - go-cqhttp 1.0.0-rc1
    - ELF_RSS 版本 2.5.6

**Comment by NekoAria** [comment]
另外开了个新的分支，请你帮忙测试一下：[v2.6.0](https://github.com/Quan666/ELF_RSS/tree/v2.6.0)
因为改了检查更新相关的逻辑，建议在最近一轮检查更新任务完成后停止机器人，删除缓存文件后再切换到这个分支。

**Comment by ddaodan** [comment]
> 另外开了个新的分支，请你帮忙测试一下：[v2.6.0](https://github.com/Quan666/ELF_RSS/tree/v2.6.0) 因为改了检查更新相关的逻辑，建议在最近一轮检查更新任务完成后停止机器人，删除缓存文件后再切换到这个分支。

问题依然存在
![HB4)8U~87}DBUDLZQ9S3RLW](https://user-images.githubusercontent.com/40017293/166677190-36a751e4-20d6-4ce2-99fb-d8c1cbfc8ee1.png)
推测是因为删推后，旧的推文顶了上来，被当成新的推送了

**Comment by NekoAria** [comment]
> > 另外开了个新的分支，请你帮忙测试一下：[v2.6.0](https://github.com/Quan666/ELF_RSS/tree/v2.6.0) 因为改了检查更新相关的逻辑，建议在最近一轮检查更新任务完成后停止机器人，删除缓存文件后再切换到这个分支。
> 
> 问题依然存在
> ![HB4)8U~87}DBUDLZQ9S3RLW](https://user-images.githubusercontent.com/40017293/166677190-36a751e4-20d6-4ce2-99fb-d8c1cbfc8ee1.png)
> 推测是因为删推后，旧的推文顶了上来，被当成新的推送了

那应该是缓存上限不够大，默认是200，你可以改成2000再看看。毕竟推特这种，一天下来会推送很多。另外你可以考虑参考 RSSHub 的文档，往订阅地址后面加一些过滤参数？如果有必要的话。

**Comment by Quan666** [comment]
改成2000也应该用处不大，rsshub的Twitter路由貌似每次返回20条左右。刚开始订阅后，出现删除推文的情况很难避免推送过时的，只能是等本地缓存的多了后，就不会了出现这种情况。
又或者是增加超过多久的消息不推送选项。

**Comment by NekoAria** [comment]
> 改成2000也应该用处不大，rsshub的Twitter路由貌似每次返回20条左右。刚开始订阅后，出现删除推文的情况很难避免推送过时的，只能是等本地缓存的多了后，就不会了出现这种情况。
> 又或者是增加超过多久的消息不推送选项。

我的意思就是只有靠堆缓存来尽可能避免。
至于超过多久不推送的选项我很早之前就想过，最主要的问题是，很多订阅给的时间并不是消息生成时间，而是消息本身带的时间。比如某些热榜类消息：V2EX热门话题，帖子本身就带时间。

**Comment by ddaodan** [comment]
我觉得可以参考一下这个项目
https://github.com/gnuf0rce/rss-helper
不太了解它是怎么获取更新的，但是没有把以前的消息推送的问题

**Comment by ddaodan** [comment]
缓存改了2000，今天一天来看没有再出现问题
不过这个问题感觉还是会出现，我先暂时不close

**Comment by NekoAria** [comment]
> 我觉得可以参考一下这个项目 [gnuf0rce/rss-helper](https://github.com/gnuf0rce/rss-helper) 不太了解它是怎么获取更新的，但是没有把以前的消息推送的问题

稍微看了下这个项目的源码，他检查更新的逻辑是基于地址和时间来的，这逻辑不适用于我们。
因为他这个设计里有考虑到消息更新的情况，所以会判断更新时间是否大于上次推送的时间，
如果大于会再推送一次更新后的消息，而这个设计我个人来说并不是很喜欢，我只想推送一次。
而且我们是支持多个 RSSHub 源的，而不同的 RSSHub 源生成的时间并不能保证是一样的。
如果采用他这个设计，那么我们就会遇到因为不同订阅源生成的时间不同而重复推送的问题。
另外再提一下，某些订阅本身带有时间信息，而不是由 RSSHub 生成的，这个情况也要考虑。
以及，如果我没理解错的话，他那个设计似乎缓存是没上限的，长期使用似乎会占用挺多空间。
总的来说，我觉得最后还是得靠堆缓存数量来尽可能避免这个问题，暂时没想到更合适的方法。

**Comment by Quan666** [comment]
#295
