### ISSUE TITLE
在没有订阅时使用“deldy”会识别为新增订阅

### ISSUE THREAD

**Issue by HsukqiLee** [Quan666/ELF_RSS#311]
1. Bug 描述
    - 复现：在没有订阅时，发送deldy xxx
    - 正常：返回“没有此订阅！”
    -  结果：返回“添加订阅成功！”
2. 截图、日志、配置、地址（issue 内上传图片或文件可直接粘贴）
    - 地址：任意
    
![19cd406a780b67f2](https://user-images.githubusercontent.com/79034142/172161745-3f8fc521-d477-40ff-984b-9ecf3d019205.png)

3. 运行环境
    - linux centos 7
    - python 3.9
    - go-cqhttp 1.0.0 rc-1
    - ELF_RSS 版本 2.6.3

如果开发者能拨冗回复此issue，将感激不尽。

**Comment by Quan666** [comment]
你在使用deldy命令前是否发送了add命令？

**Comment by HsukqiLee** [comment]
翻了一下聊天记录，是的。
机器人被风控得厉害，因此测试的时候多次add、deldy。
感谢您的回复。问题看起来解决了。
