### ISSUE TITLE
部署完后运行没有反应 [DEBUG] nonebot

### ISSUE THREAD

**Issue by lvjiawei1997** [Quan666/ELF_RSS#32]
运行后 

root@iZj6cion0j2gl790ybvbekZ:~/ELF_RSS# nb run
01-23 21:43:14 [INFO] nonebot | NoneBot is initializing...
01-23 21:43:14 [INFO] nonebot | Current Env: prod
01-23 21:43:14 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('0.0.0.0'), 'port': 8080, 'debug': True, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': None, 'superusers': {'9143411193'}, 'nickname': {'elf', 'bot'}, 'command_start': {'', '/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'showblockword': True, 'close_pixiv_cat': False, 'pixiv_referer': 'http://www.pixiv.net', 'blockword': ['互动抽奖', '微博抽奖平台'], 'baiduid': '', 'usebaidu': False, 'blockquote': True, 'version': 'v2.0.3', 'delcache': 3, 'rsshub': 'https://rsshub.app', 'rsshub_backup': ['http://rss.shab.fun', 'http://rss.shab.fun'], 'limt': 50, 'baidukey': '', 'islinux': True, 'pixiv_proxy': 'i.pximg.net', 'rss_proxy': '127.0.0.1:7890', 'zip_size': 3072}
01-23 21:43:14 [DEBUG] nonebot | Succeeded to load adapter "cqhttp"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "nonebot.plugins.base"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "RSSHUB"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "add_dy"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "change_dy"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "del_dy"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "show_all"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "show_dy"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "start"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "ELF_RSS2"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "elf_url"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "miyu"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "oneread"
01-23 21:43:14 [INFO] nonebot | Succeeded to import "ELF_URL"
01-23 21:43:14 [INFO] nonebot | Running NoneBot...
01-23 21:43:14 [DEBUG] nonebot | Loaded adapters: cqhttp
01-23 21:43:14 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
01-23 21:43:14 [INFO] uvicorn | Started reloader process [4548] using statreload
01-23 21:43:15 [INFO] nonebot | NoneBot is initializing...
01-23 21:43:15 [INFO] nonebot | Current Env: prod
01-23 21:43:15 [DEBUG] nonebot | Loaded Config: {'driver': 'nonebot.drivers.fastapi', 'host': IPv4Address('0.0.0.0'), 'port': 8080, 'debug': True, 'api_root': {}, 'api_timeout': 30.0, 'access_token': None, 'secret': None, 'superusers': {'9143411193'}, 'nickname': {'elf', 'bot'}, 'command_start': {'', '/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'blockquote': True, 'baiduid': '', 'zip_size': 3072, 'rss_proxy': '127.0.0.1:7890', 'limt': 50, 'pixiv_referer': 'http://www.pixiv.net', 'rsshub': 'https://rsshub.app', 'usebaidu': False, 'version': 'v2.0.3', 'blockword': ['互动抽奖', '微博抽奖平台'], 'delcache': 3, 'close_pixiv_cat': False, 'islinux': True, 'rsshub_backup': ['http://rss.shab.fun', 'http://rss.shab.fun'], 'showblockword': True, 'baidukey': '', 'pixiv_proxy': 'i.pximg.net'}
01-23 21:43:15 [DEBUG] nonebot | Succeeded to load adapter "cqhttp"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "nonebot.plugins.base"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "RSSHUB"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "add_dy"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "change_dy"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "del_dy"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "show_all"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "show_dy"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "start"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "ELF_RSS2"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "elf_url"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "miyu"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "oneread"
01-23 21:43:15 [INFO] nonebot | Succeeded to import "ELF_URL"
01-23 21:43:15 [INFO] uvicorn | Started server process [4551]
01-23 21:43:15 [INFO] uvicorn | Waiting for application startup.
01-23 21:43:15 [INFO] nonebot_plugin_apscheduler | Scheduler Started
01-23 21:43:15 [INFO] uvicorn | Application startup complete.

机器人没有反馈运行成功信息，请教下是什么问题

**Comment by Quan666** [comment]
你的gocqhttp启动成功了吗？
切换到最新版本，并检查主人QQ是否正确

贴log时注意隐藏配置文件信息

**Comment by lvjiawei1997** [comment]
谢提醒，gocqhttp是启动成功的，已切最新版本，qq正确，运行一样是上面的错误

**Comment by Quan666** [comment]
这并没有报错。
你的部署方式是什么？
应该是没有连接到gocqhttp，确认下go的配置是否正确，对应端口是否正确

**Comment by lvjiawei1997** [comment]
😔可以了，是我自己老眼昏花打错了true，谢谢
