### ISSUE TITLE
RSS2上传失败提醒连续刷屏

### ISSUE THREAD

**Issue by dfmjndm** [Quan666/ELF_RSS#320]
在上传失败的一瞬间刷出了十几条失败提醒
而且随着失败次数增加，刷出的失败提醒数量也增加

**Comment by dfmjndm** [comment]
是有什么缓存文件没清掉吗

**Comment by mengshouer** [comment]
之前我上传测试的都是云端已经有过的文件，都是秒传，所以没注意到

不知道nb2有没有超时机制，可能是上传太久触发超时。nb这边抛出异常，但是gocq那边还在上传。

然后定时器最大同时运行一个，因为上一个定时器异常后被关闭了，所以导致会新建一个定时器，然后又往gocq那边调用了一次api，所以异常几次上传几次

**Comment by dfmjndm** [comment]
2022/7/8——出现了UnboundLocalError

error log：

[2022-07-08 13:59:26,634 nonebot] INFO: 订阅：手动上传
[DMG] 劇場版 ソードアート·オンライン -プログレッシブ- 星なき夜のアリア [BDRip][AVC_AAC][1080P][CHS](B3F9CA24).mp4
文件大小：4.0 GB
Hash：9cc61fdf84633f0f109eb14e3bcc8556de288297
上传到群：*********   失败！请手动上传！
Job "check_down_status (trigger: interval[0:00:30], next run at: 2022-07-08 13:59:46 CST)" raised an exception
Traceback (most recent call last):
  File "/hobot/hoshino/modules/rss2/qbittorrent_download.py", line 209, in check_down_status
    await bot.call_action(
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed data=None, echo={'seq': 8}, msg='FILE_SYSTEM_UPLOAD_API_ERROR', retcode=100, status='failed', wording='server requires unsupported ftn upload'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/hobot/hoshino/modules/rss2/qbittorrent_download.py", line 220, in check_down_status
    logger.exception(e)
UnboundLocalError: local variable 'e' referenced before assignment

**Comment by mengshouer** [comment]
> 2022/7/8——出现了UnboundLocalError
> 
> error log：
> 
> [2022-07-08 13:59:26,634 nonebot] INFO: 订阅：手动上传 [DMG] 劇場版 ソードアート·オンライン -プログレッシブ- 星なき夜のアリア [BDRip][AVC_AAC][1080P][CHS](B3F9CA24).mp4 文件大小：4.0 GB Hash：9cc61fdf84633f0f109eb14e3bcc8556de288297 上传到群：********* 失败！请手动上传！ Job "check_down_status (trigger: interval[0:00:30], next run at: 2022-07-08 13:59:46 CST)" raised an exception Traceback (most recent call last): File "/hobot/hoshino/modules/rss2/qbittorrent_download.py", line 209, in check_down_status await bot.call_action( File "/usr/local/lib/python3.9/site-packages/aiocqhttp/**init**.py", line 238, in call_action return await self._api.call_action(action=action, **params) File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 178, in call_action result = await self._wsr_api.call_action(action, **params) File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 153, in call_action return _handle_api_result(await File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 38, in _handle_api_result raise ActionFailed(result=result) aiocqhttp.exceptions.ActionFailed: <ActionFailed data=None, echo={'seq': 8}, msg='FILE_SYSTEM_UPLOAD_API_ERROR', retcode=100, status='failed', wording='server requires unsupported ftn upload'>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job retval = await job.func(*job.args, **job.kwargs) File "/hobot/hoshino/modules/rss2/qbittorrent_download.py", line 220, in check_down_status logger.exception(e) UnboundLocalError: local variable 'e' referenced before assignment

草，我忘记加as e了
