### ISSUE TITLE
pip 安装时提示没有找到pydantic的相关版本

### ISSUE THREAD

**Issue by ReputationZH** [Quan666/ELF_RSS#33]
Could not find a version that satisfies the requirement pydantic~=1.7.3 (from -r requirements.txt (line 4)) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.1)
No matching distribution found for pydantic~=1.7.3 (from -r requirements.txt (line 4))

**Comment by Quan666** [comment]
请注意查看 Wiki [常见问题](https://github.com/Quan666/ELF_RSS/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
