### ISSUE TITLE
关于weibo的emoji字符错误被转换成图片的新feature请求

### ISSUE THREAD

**Issue by EUEUE39** [Quan666/ELF_RSS#334]
订阅地址：weibo/user/任意带emoji的

出错环境：weibo，任意带有emoji的微博都被大眼把emoji转换成图片

希望更新的功能：屏蔽像素过小的图片

**Comment by NekoAria** [comment]
这个取决于 ELF_RSS 的版本和 RSSHub 的版本，我记得我是实现了的。

**Comment by NekoAria** [comment]
严格说并不是 emoji ，是微博表情。

**Comment by NekoAria** [comment]
https://github.com/Quan666/ELF_RSS/blob/3b4e687e263316ec2037237272eb7be8c5aae5c4/src/plugins/ELF_RSS2/parsing/routes/weibo.py#L74

是有去除的。

**Comment by EUEUE39** [comment]
我自己折腾一下 解决后我自己关issue

**Comment by NekoAria** [comment]
> 我自己折腾一下 解决后我自己关issue

你用的 ELF_RSS 和 RSSHub 都是最新版本吗？
不提供这个信息我也没法排错。

**Comment by EUEUE39** [comment]
> > 我自己折腾一下 解决后我自己关issue
> 
> 你用的 ELF_RSS 和 RSSHub 都是最新版本吗？ 不提供这个信息我也没法排错。

elfRSS是2.4.3。rss源不清楚别人的版本，链接是https://rsshub.uneasy.win/

**Comment by NekoAria** [comment]
> > > 我自己折腾一下 解决后我自己关issue
> > 
> > 你用的 ELF_RSS 和 RSSHub 都是最新版本吗？ 不提供这个信息我也没法排错。
> 
> elfRSS是2.4.3。rss源不清楚别人的版本，链接是https://rsshub.uneasy.win/

那就是 ELF_RSS 版本太老了
