### ISSUE TITLE
作为插件加载之后，重启机器人就不推送消息了

### ISSUE THREAD

**Issue by liuzj288** [Quan666/ELF_RSS#339]
添加之后未重启是推送正常的，重启后showall命令显示是有订阅的，go-cq和nb4

**Comment by NekoAria** [comment]
你不贴出日志，我也不知道什么情况啊。

**Comment by NekoAria** [comment]
还有 ELF_RSS 本身的版本呢？

**Comment by liuzj288** [comment]
> 你不贴出日志，我也不知道什么情况啊。

加载正常，开机似乎有报错，

![image](https://user-images.githubusercontent.com/13833404/181059381-b20bf174-dfaf-41d7-a4c6-ab3b7edb434b.png)

![image](https://user-images.githubusercontent.com/13833404/181059983-390ce6da-f87f-4559-9452-b2f6f5503f0c.png)

![image](https://user-images.githubusercontent.com/13833404/181059720-fe5f06e8-cd91-4e8b-8e78-efdb0de367d7.png)

**Comment by Quan666** [comment]
你的elfrss版本呢

**Comment by liuzj288** [comment]
> 你的elfrss版本呢

就是拉的现在最新的，我是只加载的插件
![image](https://user-images.githubusercontent.com/13833404/181068230-8a4351ad-490a-4808-9312-e8d871a24444.png)

**Comment by Quan666** [comment]
> > 你的elfrss版本呢
> 
> 就是拉的现在最新的，我是只加载的插件
> ![image](https://user-images.githubusercontent.com/13833404/181068230-8a4351ad-490a-4808-9312-e8d871a24444.png)
> 

你运行pip list，把版本截图我看看

**Comment by NekoAria** [comment]
把完整的 `bot.py` 贴一下。
我怀疑是你配置的插件加载顺序有问题。

以及，你用的是自己搭建的 bot ？还是用了像是 zhenxun bot 这类集成好的 bot？

**Comment by liuzj288** [comment]
> 把完整的 `bot.py` 贴一下。 我怀疑是你配置的插件加载顺序有问题。
> 
> 以及，你用的是自己搭建的 bot ？还是用了像是 zhenxun bot 这类集成好的 bot？

自己搭建的bot，其他都是作为插件加载，这个顺序有影响吗？
![image](https://user-images.githubusercontent.com/13833404/181430533-fff181d4-4653-4861-9edd-2db7f3cebab7.png)

![image](https://user-images.githubusercontent.com/13833404/181430638-5b06d076-b964-41cd-bf60-5ea6dfbba94e.png)

**Comment by NekoAria** [comment]
> > 把完整的 `bot.py` 贴一下。 我怀疑是你配置的插件加载顺序有问题。
> > 
> > 以及，你用的是自己搭建的 bot ？还是用了像是 zhenxun bot 这类集成好的 bot？
> 
> 自己搭建的bot，其他都是作为插件加载，这个顺序有影响吗？
> ![image](https://user-images.githubusercontent.com/13833404/181430533-fff181d4-4653-4861-9edd-2db7f3cebab7.png)
> 
> ![image](https://user-images.githubusercontent.com/13833404/181430638-5b06d076-b964-41cd-bf60-5ea6dfbba94e.png)
> 

禁用其他用到 APScheduler 的插件，再重启机器人看看。
你贴的图里应该是 HarukaBot 。
我不确定这是否有影响，因为我并没装过这么多插件。

**Comment by liuzj288** [comment]
> > > 把完整的 `bot.py` 贴一下。 我怀疑是你配置的插件加载顺序有问题。
> > > 以及，你用的是自己搭建的 bot ？还是用了像是 zhenxun bot 这类集成好的 bot？
> > 
> > 
> > 自己搭建的bot，其他都是作为插件加载，这个顺序有影响吗？
> > ![image](https://user-images.githubusercontent.com/13833404/181430533-fff181d4-4653-4861-9edd-2db7f3cebab7.png)
> > ![image](https://user-images.githubusercontent.com/13833404/181430638-5b06d076-b964-41cd-bf60-5ea6dfbba94e.png)
> 
> 禁用其他用到 APScheduler 的插件，再重启机器人看看。 你贴的图里应该是 HarukaBot 。 我不确定这是否有影响，因为我并没装过这么多插件。

难道跟haruka不兼容？

**Comment by NekoAria** [comment]
> > > > 把完整的 `bot.py` 贴一下。 我怀疑是你配置的插件加载顺序有问题。
> > > > 以及，你用的是自己搭建的 bot ？还是用了像是 zhenxun bot 这类集成好的 bot？
> > > 
> > > 
> > > 自己搭建的bot，其他都是作为插件加载，这个顺序有影响吗？
> > > ![image](https://user-images.githubusercontent.com/13833404/181430533-fff181d4-4653-4861-9edd-2db7f3cebab7.png)
> > > ![image](https://user-images.githubusercontent.com/13833404/181430638-5b06d076-b964-41cd-bf60-5ea6dfbba94e.png)
> > 
> > 禁用其他用到 APScheduler 的插件，再重启机器人看看。 你贴的图里应该是 HarukaBot 。 我不确定这是否有影响，因为我并没装过这么多插件。
> 
> 难道跟haruka不兼容？

只是猜测，你不测试我们也没义务帮你解决这个问题。

**Comment by liuzj288** [comment]
> > > > > 把完整的 `bot.py` 贴一下。 我怀疑是你配置的插件加载顺序有问题。
> > > > > 以及，你用的是自己搭建的 bot ？还是用了像是 zhenxun bot 这类集成好的 bot？
> > > > 
> > > > 
> > > > 自己搭建的bot，其他都是作为插件加载，这个顺序有影响吗？
> > > > ![image](https://user-images.githubusercontent.com/13833404/181430533-fff181d4-4653-4861-9edd-2db7f3cebab7.png)
> > > > ![image](https://user-images.githubusercontent.com/13833404/181430638-5b06d076-b964-41cd-bf60-5ea6dfbba94e.png)
> > > 
> > > 
> > > 禁用其他用到 APScheduler 的插件，再重启机器人看看。 你贴的图里应该是 HarukaBot 。 我不确定这是否有影响，因为我并没装过这么多插件。
> > 
> > 
> > 难道跟haruka不兼容？
> 
> 只是猜测，你不测试我们也没义务帮你解决这个问题。

haruka卸载了还是不行
![image](https://user-images.githubusercontent.com/13833404/181553835-4be9f0f1-d147-4ad8-a503-c4d519b99800.png)

**Comment by Quan666** [comment]
你系统的时间有问题吧？

**Comment by Quan666** [comment]
把除了elf_rss以外的插件都禁用，再试试看。
你最新贴的这个日志貌似和elf_rss没关系。

**Comment by liuzj288** [comment]
> 把除了elf_rss以外的插件都禁用，再试试看。 你最新贴的这个日志貌似和elf_rss没关系。

似乎是依赖出问题了，重新装了依赖现在正常了，emmm
