### ISSUE TITLE
订阅地址中包含&符号时会出错

### ISSUE THREAD

**Issue by CiaranZhou** [Quan666/ELF_RSS#34]
订阅地址中含有"&"符号时会转义成"&amp;"，会导致实际的订阅地址与预期不符
暂不清楚是nonebot的问题还是go-cqhttp的问题

本项目、nonebot2、go-cqhttp均为当日最新版，环境是ubuntu16.04

**Comment by Quan666** [comment]
订阅地址贴一下

**Comment by CiaranZhou** [comment]
> 订阅地址贴一下

https://mikanani.me/RSS/Bangumi?bangumiId=2335&subgroupid=370
