### ISSUE TITLE
油管官方rss订阅解析报错

### ISSUE THREAD

**Issue by blyc** [Quan666/ELF_RSS#356]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

|  环境   | 版本  |
|  ----  | ----  |
| ELF_RSS | v2.6.9 |
| nonebot | 2.0.0b4 |
| Python | 3.10.4 |
| Windows | Server 2012 R2 DataCenter |

go-cqhttp是用的 https://github.com/mnixry/nonebot-plugin-gocqhttp 不太会看版本，但因为是最近部署的bot，gocq应该是1.0.0-rc3  (不好意思，如果这个gocq版本对这个error重要的话我再去试着找下版本号)

### 如何复现

订阅油管rss
https://www.youtube.com/feeds/videos.xml?channel_id=UCcamHPT05MTp8vmIp6pe7TQ
等待获取

### 期望行为

正确解析油管rss并推送

### 实际行为

![图片](https://user-images.githubusercontent.com/34291620/184480863-966d2354-392f-4ef6-9a4c-9237c48c7a00.png)

订阅地址: https://www.youtube.com/feeds/videos.xml?channel_id=UCcamHPT05MTp8vmIp6pe7TQ

_看错误似乎是utc时间格式化失败？_

**Comment by NekoAria** [comment]
无法复现，不管是在 Debian 上还是 Windows 上。

**Comment by NekoAria** [comment]
这个应该只和 ELF_RSS 处理日期的逻辑有关。

**Comment by NekoAria** [comment]
用来尝试复现的代码：

```Python
from email.utils import parsedate_to_datetime
print(parsedate_to_datetime("2022-08-12T17:55:29+00:00"))
```

相应的报错为：
```Python
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by NekoAria** [comment]
看样子是 Python 3.10 才会遇到这个问题。
看了下 CPython 的源码， `parsedate_to_datetime()` 被重构过。
