### ISSUE TITLE
在检查订阅更新时遇到 KeyError: 'title'

### ISSUE THREAD

**Issue by tkgs0** [Quan666/ELF_RSS#360]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

ELF==2.6.11
go-cqhttp==1.0.0-rc3
nonebot==2.0.0b5
Python==3.9.2
Debian 11

### 列出安装的 Python 包

aiodns==3.0.0
aiofile==3.7.4
aiofiles==0.8.0
aiohttp==3.8.1
aiosignal==1.2.0
anyio==3.6.1
appdirs==1.4.4
APScheduler==3.9.1
arrow==1.2.2
async-timeout==4.0.2
attrs==22.1.0
audioread==3.0.0
bbcode==1.1.0
beautifulsoup4==4.11.1
binaryornot==0.4.4
Brotli==1.0.9
caio==0.9.7
cchardet==2.1.7
certifi==2022.6.15
cffi==1.15.1
chardet==5.0.0
charset-normalizer==2.1.0
click==8.1.3
colorama==0.4.5
cookiecutter==1.7.3
cssselect==1.1.0
cycler==0.11.0
decorator==5.1.1
deep-translator==1.8.3
diskcache==5.4.0
emoji==2.0.0
fastapi==0.79.0
feedparser==6.0.10
fonttools==4.34.4
frozenlist==1.3.1
h11==0.12.0
httpcore==0.14.7
httptools==0.4.0
httpx==0.22.0
idna==3.3
ImageHash==4.2.1
inflect==5.6.2
Jinja2==3.1.2
jinja2-time==0.2.0
joblib==1.1.0
kiwisolver==1.4.4
langid==1.1.6
librosa==0.9.2
llvmlite==0.38.1
loguru==0.6.0
lxml==4.9.1
magneturi==1.3
MarkupSafe==2.1.1
matplotlib==3.5.3
mockingbirdforuse==0.2.3
msgpack==1.0.4
multidict==6.0.2
nb-cli==0.6.7
nonebot-adapter-onebot==2.1.3
nonebot-plugin-apscheduler==0.1.4
nonebot-plugin-guild-patch==0.2.0
nonebot-plugin-imageutils==0.1.7
nonebot2==2.0.0b5
numba==0.55.2
numpy==1.22.4
opencv-python-headless==4.6.0.66
packaging==21.3
picimagesearch==3.3.11
pikpakapi==0.0.6
Pillow==9.2.0
pooch==1.6.0
poyo==0.5.0
prompt-toolkit==3.0.30
pycares==4.2.2
pycparser==2.21
pydantic==1.9.2
pydub==0.25.1
pyfiglet==0.8.post1
pygtrie==2.5.0
pyparsing==3.0.9
pypinyin==0.47.0
pyquery==1.4.3
python-dateutil==2.8.2
python-dotenv==0.20.0
python-qbittorrent==0.4.2
python-slugify==6.1.2
pytz==2022.2.1
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.3.0
PyYAML==6.0
requests==2.28.1
resampy==0.4.0
rfc3986==1.5.0
scikit-learn==1.1.2
scipy==1.9.0
sgmllib3k==1.0.0
six==1.16.0
sniffio==1.2.0
SoundFile==0.10.3.post1
soupsieve==2.3.2.post1
starlette==0.19.1
tenacity==8.0.1
text-unidecode==1.3
threadpoolctl==3.1.0
tinydb==4.7.0
tomlkit==0.10.2
torch==1.12.1
typing_extensions==4.3.0
tzdata==2022.2
tzlocal==4.2
Unidecode==1.3.4
urllib3==1.26.11
uvicorn==0.18.2
uvloop==0.16.0
watchfiles==0.16.1
wcwidth==0.2.5
webrtcvad==2.0.10
websockets==10.3
yarl==1.8.1

### 如何复现

每次检查订阅更新时会报错  KeyError: 'title'

### 实际行为

![Screenshot_20220815_185656](https://user-images.githubusercontent.com/107618388/184624211-b7c6a114-45d1-4af3-9309-2e314d91d3bf.jpg)

**Comment by NekoAria** [comment]
能把订阅地址发一下吗？
会遇到这个情况，必然是那个订阅有问题。

**Comment by tkgs0** [comment]
> 能把订阅地址发一下吗？ 会遇到这个情况，必然是那个订阅有问题。

订阅了以下地址：

pixiv-proxy：https://github.com/Akegarasu/go-pixiv-proxy/commits/main.atom

zhenxun：https://github.com/HibiKier/zhenxun_bot/commits/main.atom

PicSearch：https://github.com/NekoAria/YetAnotherPicSearch/commits/main.atom

analysis：https://github.com/mengshouer/nonebot_plugin_analysis_bilibili/commits/master.atom

caiyunai：https://github.com/noneplugin/nonebot-plugin-caiyunai

simplemusic：https://github.com/noneplugin/nonebot-plugin-simplemusic/commits/main.atom

zx-ddcheck：https://github.com/yajiwa/zhenxun_plugin_ddcheck/commits/main.atom

zx-memes：https://github.com/yajiwa/zhenxun_plugin_memes/commits/main.atom

zx-petpet：https://github.com/yajiwa/zhenxun_plugin_petpet/commits/main.atom

zx-plugins-index：https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/commits/index.atom

zx-plugins-master：https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/commits/master.atom

**Comment by NekoAria** [comment]
> caiyunai：https://github.com/noneplugin/nonebot-plugin-caiyunai

应该是这个订阅吧。。
你换个地址再看看

**Comment by tkgs0** [comment]
> > caiyunai：https://github.com/noneplugin/nonebot-plugin-caiyunai
> 
> 应该是这个订阅吧。。 你换个地址再看看

删除该地址后没报错了，是我把地址写错了，非常抱歉打扰了，感谢您的耐心解答
