### ISSUE TITLE
请问翻译功能可以支持Deepl的api么？

### ISSUE THREAD

**Issue by dispina** [Quan666/ELF_RSS#367]
### 功能需求

希望能添加启用deelp翻译api的功能。

https://www.deepl.com/pro-api?cta=header-pro-api

### 理由

在想谷歌翻译和百度翻译的基础上多一种翻译器的选择，deelp的翻译更加口语化一些。非常感谢。

**Comment by NekoAria** [comment]
要实现不难，本来用来翻译的库就支持。
麻烦的是申请 API key 。
如果你有的话，就只是多加个配置项的事情：[DeeplTranslator](https://github.com/nidhaloff/deep-translator#id22)

**Comment by Quan666** [comment]
@dispina 试试这个分支，我没有key，你帮我测试一下，包括百度和Google都测试一下
分支：https://github.com/Quan666/ELF_RSS/tree/feat(translator)

commit：https://github.com/Quan666/ELF_RSS/commit/832ed6301c6aa2be6e78231bce937a5552b28a0a

**Comment by Quan666** [comment]
@dispina 你用过了吗？

**Comment by dispina** [comment]
感谢，测试后可以使用。
