### ISSUE TITLE
现有的消息构造逻辑（暂指推特，其他未测试）似乎有问题

### ISSUE THREAD

**Issue by Jerry-FaGe** [Quan666/ELF_RSS#37]
我看了下源码，貌似现在的消息构造逻辑大体是

- 从订阅源获取到了更新
- 写入json文件
- 构造一段消息（标题，正文str）
- 下载图片
- 结合消息和图片
- 发送

这个流程是获取到更新马上就写入本地储存的json，如果在消息构造阶段（比如下载图片）中发生问题，异常处理会直接跳过本次操作，用户不会收到任何更新推送，而本次更新已经被写入本地缓存。

这样就会导致用户在无感的情况下错过本次更新，并且程序无法在下次检查更新中知道本次出现了错误并给予用户提示。

=============================================
其实说了这么多也是想问问这个项目的代理到底是怎么用的XD，配置文件里只有一个代理地址，这个代理是用于访问订阅源还是用于图片下载的啊，比如说我关注推特福利机（大雾），如果她发一条纯文字推是可以推送的，如果发的推带图片就会出现上面的情况，因为rss源不需要代理就能访问但是图片下不了。

关于配置文件中的代理地址：比如我在机场买了一些SSR节点（配置SSR的时候需要密码），那把地址直接填到配置文件是肯定没法用的。这样的话这个代理该如何搭建或者购买呢

**Comment by Quan666** [comment]
流程已经变更，现在是推送一条写入一条，发送失败将不会写入。
代理需要你在本地运行相关软件，然后填入代理地址，一般为 `127.0.0.1:7890` 这样的地址，更多请 Google。
