### ISSUE TITLE
RSS推送是否有推送原创推特的功能？

### ISSUE THREAD

**Issue by Nenot233** [Quan666/ELF_RSS#374]
### 功能需求

RSS推送是否有推送原创推特的功能？

### 理由

一些博主恰饭转推的内容毫无营养，也会增加封号几率，所以想问问是否有这个功能

**Comment by Quan666** [comment]
不明白你这个原创指的是什么

**Comment by Nenot233** [comment]
指的是不是转发他人推、不是评论他人推

**Comment by NekoAria** [comment]
> 指的是不是转发他人推、不是评论他人推

这个在 [RSSHub 官方文档](https://docs.rsshub.app/social-media.html#twitter) 里有说啊：

| **键**            | **含义**                      | **接受的值**         | **默认值** |
|------------------|-----------------------------|------------------|---------|
| `excludeReplies` | 排除回复，只在 `/twitter/user` 中有效 | `0/1/true/false` | `false` |
| `includeRts`     | 包括转推，只在 `/twitter/user` 中有效 | `0/1/true/false` | `true`  |

**Comment by Nenot233** [comment]
非常感谢
