### ISSUE TITLE
ELF_RSS该如何添加telegram频道呢？

### ISSUE THREAD

**Issue by SilverTersand** [Quan666/ELF_RSS#381]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

最新版本，nonebot2，Python3.9

### 如何复现

根据google出来的问题，add 财经慢报 telegram/channel/Financial_Express可以成功订阅，在私聊中显示订阅成功

### 实际行为

抓取失败，后续并没有订阅消息，如果需要开启代理的话需要怎么办呢？

**Comment by Quan666** [comment]
开启代理请认真查看使用文档

**Comment by SilverTersand** [comment]
> 经更改proxy为1后成功订阅该频道，非常感谢。但仍有部分telegram频道根据上述rss格式改写后显示第一次抓取失败，请问这是什么原因呢？

**Comment by Quan666** [comment]
添加后第一次抓取没走代理？

**Comment by SilverTersand** [comment]
添加后立马就显示抓取失败了

**Comment by Quan666** [comment]
那就是因为刚添加没配置代理所以失败咯

**Comment by SilverTersand** [comment]
将proxy设为1后stop=0仍然显示抓取失败，自动停止更新；仍然有一个问题，一开始订阅好的财经慢报设置为1分钟更新一次，然而过了很久后直接发了20个消息，并且现在过了二十分组仍然没有抓取到，但是该频道几乎每分钟都有更新

**Comment by Quan666** [comment]
你的订阅链接点进去看看有没有更新

**Comment by SilverTersand** [comment]
有更新的

**Comment by Quan666** [comment]
用的rsshub.app？
