### ISSUE TITLE
希望使用bilibili rss时增加作品消息

### ISSUE THREAD

**Issue by xlive2233** [Quan666/ELF_RSS#391]
### 功能需求

通过bilibili rss 搜索
例如 add /bilibili/vsearch/嘻嘻嘻
推送时希望可以显示up主名字，目前只有简介内容

### 理由

完善推送相关功能，谢谢

**Comment by NekoAria** [comment]
原来的格式是以“链接、日期”结尾的，你的意思是加上一个“作者”（有个 tag 叫 author ，就是你这个订阅源的 up 主名）？

**Comment by xlive2233** [comment]
> 原来的格式是以“链接、日期”结尾的，你的意思是加上一个“作者”（有一个标签叫作者，就是你这个订阅源的up主名）？

你好，我的意思是在推送消息内添加up信息，比如推送是从bilibili某一个关键词搜索到的所有视频，当检测新视频进行消息推送时，在推送内容内增加up主的名字信息。这个信息应显示在简介内容之前。

**Comment by xlive2233** [comment]
> > 原来的格式是以“链接、日期”结尾的，你的意思是加上一个“作者”（有一个标签叫作者，就是你这个订阅源的up主名）？
> 
> 你好，我的意思是在推送消息内添加up信息，比如推送是从bilibili某一个关键词搜索到的所有视频，当检测新视频进行消息推送时，在推送内容内增加up主的名字信息。这个信息应显示在简介内容之前。

up是作者的意思，描述可能有点抽象。我待会补充一点图片

**Comment by xlive2233** [comment]
![X%$_90Z8@`@9KD`@S``BE)V](https://user-images.githubusercontent.com/28977537/217224552-bf58cffc-4a13-42f3-a193-b240550ac10b.png)
![TTL8TANZ0Q$%Q)NUWYL$)W1](https://user-images.githubusercontent.com/28977537/217224603-a8be04ad-070d-4e54-a48d-d83f5d844ba6.png)

**Comment by NekoAria** [comment]
我知道你的意思，不过我想的是，是只针对 b 站订阅做调整，还是统一加上 author 。
@Quan666 你觉得呢？

**Comment by xlive2233** [comment]
> 我知道你的意思，不过我想的是，是只针对 b 站订阅做调整，还是统一加上 author 。 @Quan666 你觉得呢？
author id是有的

![}A@GL5KYR(~LS@OJB1 IQ62](https://user-images.githubusercontent.com/28977537/217225904-2dc0e654-1217-4f19-879b-efe52a2a007a.png)

**Comment by xlive2233** [comment]
> 我知道你的意思，不过我想的是，是只针对 b 站订阅做调整，还是统一加上 author 。 @Quan666 你觉得呢？

另外，这些信息如果是中文应该更合理一点。
Length: 03:55
AuthorID: 471164121
Play: 166    Favorite: 7
Danmaku: 1    Comment: 1

**Comment by Quan666** [comment]
> 我知道你的意思，不过我想的是，是只针对 b 站订阅做调整，还是统一加上 author 。 @Quan666 你觉得呢？

这感觉只能是针对 b 站的做调整
