### ISSUE TITLE
适配傻妞sillyGirl机器人全平台推送

### ISSUE THREAD

**Issue by RealKiro** [Quan666/ELF_RSS#394]
### 功能需求

源代码：https://github.com/cdle/sillyGirl
Docker：https://registry.hub.docker.com/r/dswang2233/silly
傻妞官方tg群组：https://t.me/trialerr

适配傻妞机器人，以插件的形式实现微信/QQ/Telegram全平台推送

### 理由

实现微信/QQ/Telegram全平台推送

**Comment by Quan666** [comment]
本身已经支持QQ，Telegram也在计划中，微信暂时不考虑
