### ISSUE TITLE
新版本无法正常启动，提示IndexError: list index out of range

### ISSUE THREAD

**Issue by Aperove** [Quan666/ELF_RSS#396]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

腾讯云新建的轻量云服务器
系统debian11.1 python3.9.2 最新版本的ELF_RSS、go-cqhttp
nonebot是用requirements.txt安装的

反向ws连接成功以后就提示这个IndexError

superusers里面我就留了自己的QQ
留空和同时留两个人的都试过
但是都不行

### 列出安装的 Python 包

aiodns==3.0.0
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.6.2
APScheduler==3.10.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asgiref==3.6.0
asttokens==2.2.1
async-timeout==4.0.2
attrs==22.2.0
backcall==0.2.0
bbcode==1.1.0
beautifulsoup4==4.11.2
binaryornot==0.4.4
bleach==6.0.0
Brotli==1.0.9
cachetools==5.3.0
cashews==5.2.0
cchardet==2.1.7
certifi==2020.6.20
cffi==1.15.1
chardet==4.0.0
charset-normalizer==3.0.1
click==8.1.3
colorama==0.4.6
comm==0.1.2
contourpy==1.0.7
cookiecutter==2.1.1
cssselect==1.2.0
cycler==0.11.0
debugpy==1.6.6
decorator==5.1.1
deep-translator==1.10.0
defusedxml==0.7.1
distlib==0.3.6
docx2txt==0.8
elf-rss==2.6.14
emoji==2.2.0
executing==1.2.0
fastapi==0.78.0
fastjsonschema==2.16.2
feedparser==6.0.10
filelock==3.9.0
fonttools==4.38.0
fqdn==1.5.1
frozenlist==1.3.3
h11==0.12.0
httpcore==0.14.7
httplib2==0.18.1
httptools==0.5.0
httpx==0.22.0
idna==2.10
ImageHash==4.3.1
importlib-metadata==6.0.0
ipykernel==6.21.1
ipython==8.10.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
jinja2-time==0.2.0
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.5.0
jupyter-events==0.6.3
jupyter_client==8.0.2
jupyter_core==5.2.0
jupyter_server==2.2.1
jupyter_server_terminals==0.4.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
kiwisolver==1.4.4
loguru==0.6.0
lxml==4.9.2
magneturi==1.3
MarkupSafe==2.1.2
matplotlib==3.6.3
matplotlib-inline==0.1.6
mistune==2.0.5
mplfinance==0.12.9b7
msgpack==1.0.4
multidict==6.0.4
nb-cli==1.0.4
nbclassic==0.5.1
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
nonebot-adapter-onebot==2.2.1
nonebot-plugin-apscheduler==0.2.0
nonebot-plugin-guild-patch==0.2.2
nonebot2==2.0.0rc3
noneprompt==0.1.7
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.24.2
packaging==23.0
pandas==1.5.3
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
pikpakapi==0.1.1
Pillow==9.4.0
platformdirs==2.6.2
poyo==0.5.0
prometheus-client==0.16.0
prompt-toolkit==3.0.36
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pycares==4.3.0
pycparser==2.21
pycurl==7.43.0.6
pydantic==1.10.4
pyfiglet==0.8.post1
Pygments==2.14.0
pygtrie==2.5.0
pyparsing==3.0.9
pypdf==3.4.1
pyquery==2.0.0
pyrsistent==0.19.3
PySimpleSOAP==1.16.2
python-apt==2.2.1
python-dateutil==2.8.2
python-debian==0.1.39
python-debianbts==3.1.0
python-dotenv==0.21.1
python-json-logger==2.0.5
python-qbittorrent==0.4.3
python-slugify==8.0.0
pytz==2022.7.1
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.4.1
PyYAML==6.0
pyzmq==25.0.0
qtconsole==5.4.0
QtPy==2.3.0
reportbug==7.10.3+deb11u1
requests==2.28.2
rfc3339-validator==0.1.4
rfc3986==1.5.0
rfc3986-validator==0.1.1
scipy==1.10.0
Send2Trash==1.8.0
sgmllib3k==1.0.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.6.2
starlette==0.19.1
tenacity==8.1.0
terminado==0.17.1
text-unidecode==1.3
tinycss2==1.2.1
tinydb==4.7.1
tomlkit==0.11.6
tornado==6.2
traitlets==5.9.0
typing_extensions==4.4.0
tzdata==2022.7
tzlocal==4.2
uri-template==1.2.0
urllib3==1.26.5
uvicorn==0.17.6
uvloop==0.17.0
virtualenv==20.17.1
watchfiles==0.18.1
watchgod==0.8.2
wcwidth==0.2.6
webcolors==1.12
webencodings==0.5.1
websocket-client==1.5.1
websockets==10.4
widgetsnbextension==4.0.5
yarl==1.8.2
zipp==3.13.0

### 如何复现

是

### 实际行为

Traceback (most recent call last):
  File "/root/rss2/bot.py", line 11, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/usr/local/lib/python3.9/dist-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/drivers/fastapi.py", line 187, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher/matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
    await handler(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/rss2/src/plugins/ELF_RSS2/__init__.py", line 49, in start
    await send_message_to_admin(f"ELF_RSS 订阅器启动成功！\n{boot_message}", bot)
  File "/root/rss2/src/plugins/ELF_RSS2/utils.py", line 110, in send_message_to_admin
    await bot.send_private_msg(user_id=int(list(config.superusers)[0]), message=message)
IndexError: list index out of range

**Comment by Quan666** [comment]
你配置文件配置对了吗

**Comment by Aperove** [comment]
我刚才用Centos装了一遍现在正常啦，谢谢您！！
