### ISSUE TITLE
ERROR: Could not open requirements file

### ISSUE THREAD

**Issue by hot36952** [Quan666/ELF_RSS#4]
PS C:\Users\Administrator> pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.

第一步就报错，请问什么原因
部署教程对我等小白不太友好。。

**Comment by Quan666** [comment]
你一个一个的安装把，打开这个txt文件，然后 pip3 install xxx依次安装，等号前面的替换xxx

**Comment by Quan666** [comment]
报错是因为环境问题
