### ISSUE TITLE
群聊命令艾特机器人或带机器人昵称开关

### ISSUE THREAD

**Issue by Tosd0** [Quan666/ELF_RSS#400]
### 功能需求

希望在群聊中，触发命令需要艾特机器人或带机器人昵称的设置能够让用户自己选择，默认值还是为现在的需要艾特，有需要的可以改成False，感谢！(｡･ω･｡)

### 理由

每次都需要艾特机器人的话会减少效率

**Comment by Quan666** [comment]
是能用机器人昵称的

**Comment by Tosd0** [comment]
> 是能用机器人昵称的

啊，我在文档里看到了😂我标题的断句是群聊命令/艾特机器人或带机器人昵称/开关，意思是即便有机器人昵称，还是希望加一个取消这个限制的开关😂😂
