### ISSUE TITLE
希望可以设置订阅内容转变成合并转发样式

### ISSUE THREAD

**Issue by Akisama514** [Quan666/ELF_RSS#403]
### 功能需求

希望可以增加设置订阅内容转变成合并转发样式。

### 理由

1，部分订阅内容由于会定期大量更新或连续更新导致内容过长，群内使用不太方便；
2、因为也会一下子很多链接出现，与群里其他链接检索功能相关机器人也会启动，导致机器人们大量刷屏；
因为也是部分订阅会出现这样的情况，所以希望可以在订阅RSS属性里可以增加该功能开关。

**Comment by NekoAria** [comment]
理论上要实现很容易，但是具体来说，可能遇到消息内容过多导致发送失败的情况。

所以如果发送失败，还是要转为逐条发送。如果你觉得这个逻辑可以接受，那我就加上。

**Comment by Akisama514** [comment]
我觉得可以的，如果出现发送失败的情况也可以自己选择关闭这个功能

**Comment by NekoAria** [comment]
你试试 `issue_403` 这个分支？

我几乎没在用这个插件了，所以也不好测试。

启用指令 `change 订阅名 forward=1` 。

**Comment by Akisama514** [comment]
推特测试连发了几条，都是就几个字的推文，即使把订阅forward=0也依然会结果出现错误
03-07 09:27:15 [INFO] ELF_RSS2 | 我的订阅 检查更新
03-07 09:28:19 [WARNING] apscheduler | Execution of job "check_update (trigger: interval[0:01:00], next run at: 2023-03-07 09:28:19 CST)" skipped: maximum number of running instances reached (1)
03-07 09:29:21 [WARNING] apscheduler | Execution of job "check_update (trigger: interval[0:01:00], next run at: 2023-03-07 09:29:21 CST)" skipped: maximum number of running instances reached (1)
03-07 09:30:27 [WARNING] apscheduler | Execution of job "check_update (trigger: interval[0:01:00], next run at: 2023-03-07 09:30:27 CST)" skipped: maximum number of running instances reached (1)
03-07 09:31:28 [WARNING] apscheduler | Execution of job "check_update (trigger: interval[0:01:00], next run at: 2023-03-07 09:31:28 CST)" skipped: maximum number of running instances reached (1)
03-07 09:32:15 [ERROR] ELF_RSS2 | 我的订阅 检查更新超时，结束此次任务!

**Comment by NekoAria** [comment]
把 `bot.send_forward_msg()` 写成 `bot.send_forward_message()` 了。。

你再试试新的一次提交？我试了下，应该是没什么问题了。

**Comment by Akisama514** [comment]
可以了，谢谢大佬。
