### ISSUE TITLE
希望增加启动私聊开关

### ISSUE THREAD

**Issue by Tosd0** [Quan666/ELF_RSS#412]
### 功能需求

如题，希望增加启动私聊开关。每次机器人启动后都会给主人发一次消息，希望能出一个配置开关。
![E32845CF-FE6B-49A9-8BEA-0D3D2AD14554](https://user-images.githubusercontent.com/65720409/227778031-d4a6aa07-be26-4cfd-8e13-87fa3f4683da.jpeg)

### 理由

在偶尔频繁重启bot的时候有些刷屏

**Comment by Quan666** [comment]
别频繁重启不就成了

**Comment by Tosd0** [comment]
> 别频繁重启不就成了

如果在测试插件或者改配置就会有点刷屏（泪）

**Comment by NekoAria** [comment]
才看到。明天加个配置项吧。
