### ISSUE TITLE
change命令可以支持通配符吗

### ISSUE THREAD

**Issue by fengpan0403** [Quan666/ELF_RSS#420]
### 功能需求

change命令可以支持通配符吗？很多订阅修改推送qun只能一个个去修改，能不能支持通配符啊？

### 理由

change命令可以支持通配符吗？很多订阅修改推送qun只能一个个去修改，能不能支持通配符啊？

**Comment by NekoAria** [comment]
我感觉没必要吧，你可以用 `change a,b,c qun=` 这种方式批量修改多个订阅的 qun 。
