### ISSUE TITLE
不知道为什么有个奇怪订阅，怎么也删除不了，还会不停提示报错。

### ISSUE THREAD

**Issue by lintonxue00** [Quan666/ELF_RSS#424]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

昨天更新过应该是最新的版本，不知道为什么有个奇怪订阅，怎么也删除不了，还会不停提示报错。
![image](https://user-images.githubusercontent.com/115356968/233791607-38c3555f-83ea-4565-9591-27ca9347003d.png)
我不知道该怎么删除它，麻烦求解下，在哪里可以找到订阅配置删除这个订阅

### 如何复现

![image](https://user-images.githubusercontent.com/115356968/233791497-d019d88d-e6f4-43d9-b45f-72607f5baded.png)
![image](https://user-images.githubusercontent.com/115356968/233791529-b8e71de1-1e7c-4e90-b70d-e9a4e96e8756.png)

### 期望行为

（已停止）：有
取消这个订阅，这显然不是个正常的订阅链接

### 实际行为

删除不了，一直报错，不知道哪里删除，难道我要重装？

**Comment by lintonxue00** [comment]
ebot_plugin_naturel_gpt.matcher) running complete                 04-22 22:52:52 [INFO] ELF_RSS2 | 最近更新番剧 检查更新            04-22 22:52:53 [INFO] ELF_RSS2 | 最近更新番剧 没有新信息          04-22 22:53:01 [INFO] ELF_RSS2 |  检查更新                        04-22 22:53:02 [ERROR] ELF_RSS2 | [https://rsshub.app/有]访问失败 ！                                                                04-22 22:53:02 [WARNING] ELF_RSS2 |  抓取失败！                   04-22 22:53:04 [INFO] nonebot_plugin_pixivbot | [watchman] triggered "[rsdn6] user_illusts by onebot:None:282914476 (user_id=177784)"

**Comment by NekoAria** [comment]
已经停止的订阅名前面会显示 `（已停止）` 。
我不知道你是怎么添加这个订阅名为空的订阅的。。

只能去 data 目录下的 rss.json 文件里删除这个订阅，然后重启 bot 。

你找到这个订阅后，把它的订阅名发一下。
大概是空格还是空字符串？

**Comment by NekoAria** [comment]
我还不知道你是怎么添加这个订阅名为空的订阅的，你怎么就直接关了这个 issue 。
