### ISSUE TITLE
订阅无结果,但是疯狂跑流量

### ISSUE THREAD

**Issue by sherlockHlb** [Quan666/ELF_RSS#429]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

均是最新版+py3.11

### 如何复现

订阅了就疯狂波动式跑流量,一天能跑几十G,但是没有内容发出,订阅文件如下
[rss.json.txt](https://github.com/Quan666/ELF_RSS/files/11359884/rss.json.txt)

[yzwm.json.txt](https://github.com/Quan666/ELF_RSS/files/11359885/yzwm.json.txt)

[yzym.json.txt](https://github.com/Quan666/ELF_RSS/files/11359886/yzym.json.txt)

[P站关注.json.txt](https://github.com/Quan666/ELF_RSS/files/11359883/P.json.txt)

### 实际行为

![image](https://user-images.githubusercontent.com/30238046/235319368-e80cac94-a800-4f45-990d-01ec04a9ce87.png)

**Comment by sherlockHlb** [comment]
即便是下载p站图片,一共也就下载了1G不到,
跑了30G流量...

**Comment by Quan666** [comment]
提供的信息无法判断是该插件造成的，请自己验证清楚后再来提交 issue

**Comment by sherlockHlb** [comment]
确认是插件造成的,把那几个订阅关闭后,流量不跑了.从凌晨到现在,仍然是2.3g
现在正在分别打开订阅以测试究竟是哪个rss订阅导致的还是插件问题导致的
是否有办法查看"检查更新"和"下载"的相关log?
