### ISSUE TITLE
请问是否能部署在树莓派，安装依赖时出错

### ISSUE THREAD

**Issue by kksmi** [Quan666/ELF_RSS#43]
安装依赖时出现libxml，lxml相关错误，但系统软件lxml已是最新版本

**Comment by Quan666** [comment]
请把详细的错误日志放上来

**Comment by kksmi** [comment]
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kibdvgb8/lxml_2ba40e255457415f801991610ccfbde0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kibdvgb8/lxml_2ba40e255457415f801991610ccfbde0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ciz6bup3
         cwd: /tmp/pip-install-kibdvgb8/lxml_2ba40e255457415f801991610ccfbde0/
    Complete output (3 lines):
    Building lxml version 4.6.0.
    Building without Cython.
    Error: Please make sure the libxml2 and libxslt development packages are installed.
    ----------------------------------------


 Running setup.py install for lxml ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kibdvgb8/lxml_b2bb4a6cd2ff41c6a881dff4f713378f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kibdvgb8/lxml_b2bb4a6cd2ff41c6a881dff4f713378f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hc7pt3d5/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.8/lxml
         cwd: /tmp/pip-install-kibdvgb8/lxml_b2bb4a6cd2ff41c6a881dff4f713378f/
    Complete output (96 lines):
    Building lxml version 4.5.0.
    Building without Cython.
    ERROR: b'/bin/sh: 1: xslt-config: not found\n'
    ** make sure the development packages of libxml2 and libxslt are installed **



compilation terminated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kibdvgb8/lxml_b2bb4a6cd2ff41c6a881dff4f713378f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kibdvgb8/lxml_b2bb4a6cd2ff41c6a881dff4f713378f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hc7pt3d5/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.8/lxml Check the logs for full command output.

**Comment by Quan666** [comment]
https://kinegratii.github.io/2017/05/14/install-lxml-on-respberry-pi/
参考这个试试看能不能解决。我手头也没有树莓派来测试

**Comment by kksmi** [comment]
谢谢

**Comment by kksmi** [comment]
请问这是nonebot没有配置好吗 
nonebot.init()
  File "/home/pi/.local/lib/python3.8/site-packages/nonebot/__init__.py", line 175, in init
    env = Env()
  File "/home/pi/.local/lib/python3.8/site-packages/nonebot/config.py", line 38, in __init__
    __pydantic_self__).__init__(**__pydantic_self__._build_values(
  File "/home/pi/.local/lib/python3.8/site-packages/nonebot/config.py", line 53, in _build_values
    return deep_update(self._build_secrets_files(_secrets_dir),
TypeError: 'NoneType' object is not callable

**Comment by Quan666** [comment]
运行
pip install --force-reinstall pydantic==1.7.3

**Comment by kksmi** [comment]
非常感谢，想请问一下nonebot按照设置运行之后，会出现连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/cqhttp/ws 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 的情况；
机器人在运行时也有报[ERROR] nonebot | WebSocket disconnected by peer.是什么原因，应该如何解决呢
运行之后订阅做了发推特测试没有收到推送，想请问机器人是实时推送的吗

**Comment by kksmi** [comment]
你好，在检测更新时出现了这样的错误，订阅地址没有错误，但出现了以下报错是否必须设置cookies

抓取失败！将重试 5 次！多次失败请检查订阅地址 https://rsshub.app/twitter/user/xxxxxx！
如果设置了 cookies 请检查 cookies 正确性
03-06 15:14:41 [ERROR] apscheduler | Job "check_update (trigger: interval[0:05:00], next run at: 2021-03-06 15:18:42 CST)" raised an exception
Traceback (most recent call last):
  File "src/plugins/ELF_RSS2/RSSHUB/RSS_Parsing.py", line 194, in get_rss
    if d.entries:
UnboundLocalError: local variable 'd' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "src/plugins/ELF_RSS2/RSSHUB/rsstrigger.py", line 14, in check_update
    await RSS_Parsing.start(rss)
  File "src/plugins/ELF_RSS2/RSSHUB/RSS_Parsing.py", line 67, in start
    new_rss = await get_rss(rss)
  File "src/plugins/ELF_RSS2/RSSHUB/RSS_Parsing.py", line 199, in get_rss
    raise BaseException
BaseException

**Comment by Quan666** [comment]
你的订阅地址是能正确访问的吗？还有rsshub.app已经被墙了

**Comment by kksmi** [comment]
是的，能正确访问出信息来，树莓派爬了梯子的

**Comment by kksmi** [comment]
想问一下连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/cqhttp/ws 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 的情况是什么意思

**Comment by Quan666** [comment]
你要确保你gocq是正常运行的

**Comment by kksmi** [comment]
目前已经可以进行消息推送了，就是大概一个小时后才发一个小时前的消息，这可能是什么原因呢

**Comment by Quan666** [comment]
rsshub的缓存时间太长，自己建个rsshub吧
