### ISSUE TITLE
希望添加图片二次(等待)载入功能

### ISSUE THREAD

**Issue by sherlockHlb** [Quan666/ELF_RSS#434]
### 功能需求

希望添加延迟,针对图片二次载入或者添加载入等待.

### 理由

有的网站RSS订阅防盗链,先上一个载入图片,再进行载入图片.
导致获取到的是载入图片

**Comment by Quan666** [comment]
描述清楚

**Comment by sherlockHlb** [comment]
也就是,网页会先加载https://*.com/wp-content/themes/CorePress/static/img/loading.gif
进行占位,然后再加载真实图片地址来替换.
插件获取到的就是这个loading.gif图片.
我看看代码如何获取内容的.

**Comment by sherlockHlb** [comment]
之前我写的一个插件是通过添加time.sleep()等待容器载入完成
再获取一次内容,实现这个效果

**Comment by Quan666** [comment]
这种只能针对某个网站做适配，你会写代码的话可以自己实现然后提交pr

**Comment by sherlockHlb** [comment]
添加一个等待载入参数是否可行.
等待N秒后再次获取网页源码.
不知道aiohttp能不能实现动态载入,我用的是selenium

**Comment by Quan666** [comment]
不行
