### ISSUE TITLE
希望添加主动查询的功能

### ISSUE THREAD

**Issue by a930389426** [Quan666/ELF_RSS#437]
### 功能需求

希望能添加主动查询的功能，比如”查询+订阅名“即可获取某个订阅的最新消息，如果可以的话加数量获取对应数量的消息，比如”查询+次数+订阅名“获取某个订阅最新的X条消息

### 理由

我这边有个游戏群，会随机出现限时的活动，而出现前的一个小时，官方的推特会发送消息，但一个小时太长了，消息容易被群友给刷走，所以希望加个主动查询的功能，让没及时看到推送的群友能知道过段时间到底会不会出这个活动

**Comment by NekoAria** [comment]
这种事情本来应该用类似 Telegram 或 Discord 里的频道来实现，而 QQ 频道现在还没开放。

所以可行又简单的方案是，另外创建一个群，然后禁止非管理员发言，就只作为官推消息转发推送群或公告群来使用。
