### ISSUE TITLE
有可以部署到Hoshinobot的版本吗

### ISSUE THREAD

**Issue by Kaltsit-02** [Quan666/ELF_RSS#440]
### 功能需求

找了好久都没找到可以部署到Hoshino上的Twitter转发插件

### 理由

用了好久Hoshino了，不太想换框架

**Comment by NekoAria** [comment]
@mengshouer 有基于这个插件写一个适配 Hoshino 的 RSS 插件，叫 rss2 ： [HoshinoBot-Plugins](https://github.com/mengshouer/HoshinoBot-Plugins)
你先试试？
不过他几个月没更新了。

**Comment by mengshouer** [comment]
我看咖啡佬好像在写nonebot2的hoshino插件，如果出了，并且功能符合我要求的话我可能会完全抛弃hoshino，然后仓库可能会归档，然后移植插件到nb2上面了（

然后我没更新的原因是我没遇到什么bug，可能是我自己用的里面的功能不多的问题吧，然后也没有issue，最后加上懒（

**Comment by Kaltsit-02** [comment]
谢谢，我先试试上面那个
