### ISSUE TITLE
请问我想在某个订阅中追加群号应该如何操作

### ISSUE THREAD

**Issue by ElainaFanBoy** [Quan666/ELF_RSS#443]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

最新版本，nb2rc4，py3.9.12

### 如何复现

change xxx qun=,123456789

### 实际行为

❌ 禁止在群组中修改订阅账号！如要取消订阅请使用 deldy 命令！

**Comment by NekoAria** [comment]
你如果有对这个 bot 的 superuser 权限，就可以通过私聊 bot 用 change 指令添加订阅的群。
不然，只能通过手动在要添加订阅的那个群里用 add 指令额外添加一个新的订阅。

**Comment by ElainaFanBoy** [comment]
> 你如果有对这个 bot 的 superuser 权限，就可以通过私聊 bot 用 change 指令添加订阅的群。
> 不然，只能通过手动在要添加订阅的那个群里用 add 指令额外添加一个新的订阅。

我有su的情况下私聊bot没反应是咋回事，但是log显示已经running complete了

**Comment by NekoAria** [comment]
按理说会返回一条确定修改成功的消息。
你看看 gocqhttp 或者其他上游端的日志？

**Comment by ElainaFanBoy** [comment]
> 按理说会返回一条确定修改成功的消息。
> 你看看 gocqhttp 或者其他上游端的日志？

应该是gocq的锅
