### ISSUE TITLE
获取内容失败

### ISSUE THREAD

**Issue by veadex** [Quan666/ELF_RSS#451]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

都是最新的

### 列出安装的 Python 包

aiodns==3.0.0
aiofiles==23.1.0
aiohttp==3.8.4
aiohttp-socks==0.8.0
aiosignal==1.3.1
aiosqlite==0.18.0
alembic==1.10.4
anyio==3.6.2
APScheduler==3.10.1
arrow==1.2.3
async-generator==1.10
async-timeout==4.0.2
asyncache==0.3.1
asyncio==3.4.3
attrs==22.2.0
bbcode==1.1.0
beautifulsoup4==4.12.2
binaryornot==0.4.4
BingImageCreator==0.1.2.1
Brotli==1.0.9
build==0.10.0
CacheControl==0.12.11
cachetools==5.3.1
cashews==6.0.2
certifi==2022.12.7
cffi==1.15.1
chardet==3.0.4
charset-normalizer==3.1.0
cleo==2.0.1
click==8.1.3
colorama==0.4.6
contourpy==1.0.7
cookiecutter==2.2.3
crashtest==0.4.1
cssselect==1.2.0
cycler==0.11.0
dateparser==1.1.8
deep-translator==1.11.4
Deprecated==1.2.13
distlib==0.3.6
dulwich==0.21.3
EdgeGPT==0.2.1
emoji==2.6.0
exceptiongroup==1.1.1
fastapi==0.95.1
feedparser==6.0.10
filelock==3.11.0
filetype==1.2.0
fonttools==4.39.3
frozendict==2.3.8
frozenlist==1.3.3
googletrans==3.0.0
greenlet==2.0.1
h11==0.12.0
h2==3.2.0
hikari-bot==0.3.9.3
hpack==3.0.0
hstspreload==2023.1.1
html5lib==1.1
httpcore==0.14.7
httptools==0.5.0
httpx==0.22.0
httpx-socks==0.7.5
hyper==0.7.0
hyperframe==5.2.0
idna==2.10
ImageHash==4.3.1
importlib-metadata==6.3.0
installer==0.7.0
jaraco.classes==3.2.3
Jinja2==3.1.2
jinja2-time==0.2.0
jsonschema==4.17.3
keyring==23.13.1
kiwisolver==1.4.4
lazy==1.5
libretranslatepy==2.1.1
lockfile==0.12.2
loguru==0.6.0
lxml==4.9.2
magneturi==1.3
Mako==1.2.4
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.7.1
mdurl==0.1.2
meme-generator==0.0.11
more-itertools==9.1.0
msgpack==1.0.5
multidict==6.0.4
nb-cli==1.1.2
nonebot-adapter-onebot==2.2.3
nonebot-plugin-access-control==0.4.1
nonebot-plugin-apscheduler==0.3.0
nonebot-plugin-capoo==0.1.2
nonebot-plugin-datastore==0.6.3
nonebot-plugin-guild-patch==0.2.3
nonebot-plugin-htmlrender==0.2.0.3
nonebot-plugin-localstore==0.4.1
nonebot-plugin-memes==0.4.6
nonebot-plugin-picsearcher==0.1.10
nonebot-plugin-pixivbot==1.8.4
nonebot-plugin-reboot==0.1.3
nonebot-plugin-trace-moe==0.1.0
nonebot-plugin-xiuxian==0.4.33
nonebot2==2.0.0
noneprompt==0.1.9
ntplib==0.4.0
numpy==1.24.3
openai==0.27.4
OpenAIAuth==0.3.6
opencv-python-headless==4.7.0.72
orjson==3.8.12
outcome==1.2.0
packaging==23.1
paho-mqtt==1.6.1
pexpect==4.8.0
pikpakapi==0.1.1
pil-utils==0.1.7
Pillow==10.0.0
ping3==4.0.4
PixivPy-Async==1.2.14
pkginfo==1.9.6
platformdirs==2.6.2
playwright==1.32.1
poetry==1.4.2
poetry-core==1.5.2
poetry-plugin-export==1.3.0
prompt-toolkit==3.0.38
ptyprocess==0.7.0
pycares==4.3.0
pycparser==2.21
pydantic==1.10.11
pyee==9.0.4
pyfiglet==0.8.post1
Pygments==2.15.1
pygtrie==2.5.0
pymdown-extensions==9.11
pyparsing==3.0.9
pypinyin==0.48.0
pyproject_hooks==1.0.0
pyquery==2.0.0
pyrsistent==0.19.3
PySocks==1.7.1
python-dateutil==2.8.2
python-dotenv==1.0.0
python-markdown-math==0.8
python-multipart==0.0.5
python-qbittorrent==0.4.3
python-slugify==8.0.1
python-socks==2.2.0
pytz==2023.3
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.4.1
pywin32-ctypes==0.2.0
PyYAML==6.0
rapidfuzz==2.15.1
regex==2023.3.23
requests==2.28.2
requests-toolbelt==0.10.1
revChatGPT==4.2.5
rfc3986==1.5.0
rich==13.3.4
scipy==1.11.1
selenium==4.10.0
sgmllib3k==1.0.0
shellingham==1.5.0.post1
shortuuid==1.0.11
six==1.16.0
sniffio==1.3.0
socksio==1.0.0
sortedcontainers==2.4.0
soupsieve==2.4.1
SQLAlchemy==2.0.13
starlette==0.26.1
tenacity==8.2.2
text-unidecode==1.3
tiktoken==0.3.3
tinydb==4.8.0
toml==0.10.2
tomlkit==0.11.7
tqdm==4.65.0
translate==3.6.1
trio==0.22.0
trio-websocket==0.10.3
trove-classifiers==2023.3.9
typing_extensions==4.5.0
tzdata==2023.3
tzlocal==4.3
urllib3==1.26.15
uvicorn==0.21.1
virtualenv==20.17.1
watchfiles==0.19.0
wcwidth==0.2.6
webencodings==0.5.1
websockets==11.0.2
win32-setctime==1.1.0
wrapt==1.15.0
wsproto==1.2.0
yarl==1.9.2
zipp==3.15.0

### 如何复现

添加订阅之后正常检查更新时会报错

### 期望行为

正常发送订阅

### 实际行为

抱错`Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "C:\Users\Administrator\Desktop\test\first\.venv\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\test\first\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\test\first\.venv\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\Desktop\test\first\.venv\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 604, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\Desktop\test\first\.venv\Lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\Administrator\Desktop\test\first\first_test\plugins\ELF_RSS2\my_trigger.py", line 21, in check_update
    await rss_parsing.start(rss)
  File "C:\Users\Administrator\Desktop\test\first\first_test\plugins\ELF_RSS2\rss_parsing.py", line 115, in start
    await pr.start(rss_name=rss.name, new_rss=new_rss)
  File "C:\Users\Administrator\Desktop\test\first\first_test\plugins\ELF_RSS2\parsing\parsing_rss.py", line 186, in start
    rss_title = new_rss["feed"]["title"]
  File "C:\Users\Administrator\Desktop\test\first\.venv\Lib\site-packages\feedparser\util.py", line 113, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'title'`

**Comment by NekoAria** [comment]
你这个订阅的地址呢？
从报错来看，是没有获取到标题。

**Comment by veadex** [comment]
> 你这个订阅的地址呢？
> 从报错来看，是没有获取到标题。

地址是https://rsshub.app/weibo/user/6333407356，也尝试了直接输入微博的地址也不行，没有试别的平台

**Comment by NekoAria** [comment]
你配置代理了吗？
不过按理说，如果没配置代理，更早就会有获取失败的日志。

**Comment by veadex** [comment]
配置了一个日本的代理，服务器是自己的，IP应该没问题



---- 回复的原邮件 ----
| 发件人 | Neko ***@***.***> |
| 日期 | 2023年07月12日 17:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Quan666/ELF_RSS] 获取内容失败 (Issue #451) |

你配置代理了吗？
不过按理说，如果没配置代理，更早就会有获取失败的日志。

**Comment by veadex** [comment]
报错又变了，我在服务器上能访问，但是nb访问不了`https://rsshub.app/weibo/user/6333407356`
![Screenshot_2023-07-12-17-37-52-276_com.oray.sunlogin.jpg](https://github.com/Quan666/ELF_RSS/assets/65024689/c680fd30-75c0-486a-a7cb-f89563d599ff)


`'change 111 stop=0'
07-12 17:34:39 [INFO] nonebot | Event will be handled by Matcher(type='message', module=hikari_bot)
07-12 17:34:39 [INFO] nonebot | Event will be handled by Matcher(type='message', module=first_test.plugins.ELF_RSS2.command.change_dy)
07-12 17:34:39 [INFO] nonebot | Matcher(type='message', module=hikari_bot) running complete
07-12 17:34:39 [INFO] ELF_RSS2 | 定时任务 111 添加成功
07-12 17:34:39 [INFO] ELF_RSS2 | 111 检查更新
07-12 17:34:42 [ERROR] ELF_RSS2 | [https://rsshub.app/weibo/user/6333407356]访问失败！
07-12 17:34:42 [WARNING] ELF_RSS2 | 111 抓取失败！`

**Comment by veadex** [comment]
> 报错又变了，我在服务器上能访问，但是nb访问不了`https://rsshub.app/weibo/user/6333407356`
> ![Screenshot_2023-07-12-17-37-52-276_com.oray.sunlogin.jpg](https://github.com/Quan666/ELF_RSS/assets/65024689/c680fd30-75c0-486a-a7cb-f89563d599ff)
> 
> 
> `'change 111 stop=0'
> 07-12 17:34:39 [INFO] nonebot | Event will be handled by Matcher(type='message', module=hikari_bot)
> 07-12 17:34:39 [INFO] nonebot | Event will be handled by Matcher(type='message', module=first_test.plugins.ELF_RSS2.command.change_dy)
> 07-12 17:34:39 [INFO] nonebot | Matcher(type='message', module=hikari_bot) running complete
> 07-12 17:34:39 [INFO] ELF_RSS2 | 定时任务 111 添加成功
> 07-12 17:34:39 [INFO] ELF_RSS2 | 111 检查更新
> 07-12 17:34:42 [ERROR] ELF_RSS2 | [https://rsshub.app/weibo/user/6333407356]访问失败！
> 07-12 17:34:42 [WARNING] ELF_RSS2 | 111 抓取失败！`

代理地址是http://127.0.0.1:10809

**Comment by veadex** [comment]
报错又变了，我在服务器上能访问，但是nb访问不了`https://rsshub.app/weibo/user/6333407356`
![Screenshot_2023-07-12-17-37-52-276_com.oray.sunlogin.jpg](https://github.com/Quan666/ELF_RSS/assets/65024689/c680fd30-75c0-486a-a7cb-f89563d599ff)


`'change 111 stop=0'
07-12 17:34:39 [INFO] nonebot | Event will be handled by Matcher(type='message', module=hikari_bot)
07-12 17:34:39 [INFO] nonebot | Event will be handled by Matcher(type='message', module=first_test.plugins.ELF_RSS2.command.change_dy)
07-12 17:34:39 [INFO] nonebot | Matcher(type='message', module=hikari_bot) running complete
07-12 17:34:39 [INFO] ELF_RSS2 | 定时任务 111 添加成功
07-12 17:34:39 [INFO] ELF_RSS2 | 111 检查更新
07-12 17:34:42 [ERROR] ELF_RSS2 | [https://rsshub.app/weibo/user/6333407356]访问失败！
07-12 17:34:42 [WARNING] ELF_RSS2 | 111 抓取失败！`
明白怎么回事了，代理配置错误
