### ISSUE TITLE
发送消息失败后能否尝试隔一段时间后重新发送

### ISSUE THREAD

**Issue by hutuY** [Quan666/ELF_RSS#452]
### 功能需求

> 07-13 20:41:48 [ERROR] ELF_RSS2 | E: ActionFailed(data=None, echo='1035', message='send group message failed: blocked by server', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='send group message failed: blocked by server')
> 消息发送失败！
发送消息失败后能否尝试隔一段时间后重新发送

### 理由

消息发送失败之后不会重新发送，从而错过消息

**Comment by NekoAria** [comment]
事实上是有重试机制的，不过具体来说，有分两种情况：

1. 对其中一个订阅者消息发送失败，之后并不会重试

2. 对这个订阅的所有订阅者全部发送失效，才会判定为发送失败，在下次检查更新的时候，会再次尝试发送一次，如果还是失败，后续就不管了

**Comment by NekoAria** [comment]
而且，第二种情况会在下次重试发送失败的时候，立马尝试发送一条带消息链接的错误提示信息
