### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by liuzj288** [Quan666/ELF_RSS#458]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

ELF_RSS v2.6.20
Python 2.10.11

### 如何复现

清空rss重新添加依然出现报错
pip install -r requirement.txt
重装依赖后依然相同报错

### 实际行为

![image](https://github.com/Quan666/ELF_RSS/assets/13833404/c4efc964-8a68-4348-a65a-d944000a6d0d)

**Comment by NekoAria** [comment]
bot 没加过群吗？就算是这样，也不该会是 None ，而应该是空的 list 才对。

**Comment by liuzj288** [comment]
> bot 没加过群吗？就算是这样，也不该会是 None ，而应该是空的 list 才对。
好几个群呢，难道是某些群的权限问题？

**Comment by Quan666** [comment]
gocq启动成功并连上elfrss了吗

**Comment by liuzj288** [comment]
> gocq启动成功并连上elfrss了吗

emmm，排查一圈应该不是这边的原因
