### ISSUE TITLE
成功添加订阅但是抓取失败，访问失败

### ISSUE THREAD

**Issue by xiaoli-19** [Quan666/ELF_RSS#460]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

ELF_RSS:V2.6.20 ,go-cqhttp:8.9.63 ,nonebot:2.0.1,Python:3.10.10

### 如何复现

能复现，每次都是添加订阅成功，过几秒钟第一次抓取失败

### 实际行为

![image](https://github.com/Quan666/ELF_RSS/assets/125441426/1e428a53-4dfa-420b-bbc0-c974ef8d1cdc)
![image](https://github.com/Quan666/ELF_RSS/assets/125441426/e94121fc-d21b-4e1b-a884-903bd8edf1dd)

**Comment by NekoAria** [comment]
这不就是订阅源的问题，你找我们有什么用？。。

**Comment by xiaoli-19** [comment]
奥，抱歉

**Comment by xiaoli-19** [comment]
为什么我换了b站抓取失败报错404，微博报错Cannot read properties of undefined (reading 'screen_name')

**Comment by NekoAria** [comment]
你去 RSSHub 那问啊，问我们有什么用？
