### ISSUE TITLE
RSS 订阅检查更新问题

### ISSUE THREAD

**Issue by heitu001** [Quan666/ELF_RSS#48]
订阅第三方https://yande.re/post/piclens?page=
运行一段时间就会出现
 [WARNING] apscheduler | Execution of job "check_update (trigger: interval[0:05:00], next run at: 2021-03-13 18:58:47 CST)" skipped: maximum number of running instances reached (1)

**Comment by Quan666** [comment]
和某个订阅地址关系不大，复现方式未知

**Comment by Quan666** [comment]
配置文件中增加以下配置好像能缓解问题
```
apscheduler_config={ "apscheduler.timezone": "Asia/Shanghai", "apscheduler.executors.processpool": {"type": "processpool","max_workers": "61"}}
```

**Comment by heitu001** [comment]
@Quan666 好的~我更新试试 谢谢

**Comment by LucyChao233** [comment]
你好！我最近在开发一个推送的插件的时候也遇到了上述问题，在爬取境外网站时由于时间过长而导致apscheduler自动skip，目前将httpx的timeout设置为none虽然有一点点的缓解但是还是在一段时间过后不再运行（3-4天），请问你是否有找到完全解决的方案？或者是否有能大幅缓解的方案？谢谢。

**Comment by Quan666** [comment]
> 你好！我最近在开发一个推送的插件的时候也遇到了上述问题，在爬取境外网站时由于时间过长而导致apscheduler自动skip，目前将httpx的timeout设置为none虽然有一点点的缓解但是还是在一段时间过后不再运行（3-4天），请问你是否有找到完全解决的方案？或者是否有能大幅缓解的方案？谢谢。

你加了我上面说的那个配置了吗？

**Comment by LucyChao233** [comment]
> > 你好！我最近在开发一个推送的插件的时候也遇到了上述问题，在爬取境外网站时由于时间过长而导致apscheduler自动skip，目前将httpx的timeout设置为none虽然有一点点的缓解但是还是在一段时间过后不再运行（3-4天），请问你是否有找到完全解决的方案？或者是否有能大幅缓解的方案？谢谢。
> 
> 你加了我上面说的那个配置了吗？

暂时没有，因为我预估这样也只是暂时解决，但也应该会比之前好一些，只是想问一下有没有彻底的解决方案。另外这个配置是在env里面加就行了吗，我用到apscheduler的插件，但是并没有用的你的插件。

**Comment by Quan666** [comment]
你加了试一试，具体怎么加你可以看官方文档。
还有你可以把请求超时时间设置的小于定时任务周期。
