### ISSUE TITLE
Pikpak每日云上传使用次数达上限会无限报错

### ISSUE THREAD

**Issue by Katou-Kouseki** [Quan666/ELF_RSS#481]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

Docker部署

### 如何复现

Pikpak登录查询获悉，多次云上传达到每日次数上限

### 期望行为

提示当日pikpak达上限，不会再无限报错

### 实际行为

![image](https://github.com/Quan666/ELF_RSS/assets/30703483/d0abc52b-e272-49a8-9505-c5dede2183d4)

**Comment by Quan666** [comment]
你订阅的什么，这么容易超限制
