### ISSUE TITLE
请求增加功能: 只转发包含图片的推特

### ISSUE THREAD

**Issue by railannad** [Quan666/ELF_RSS#5]
场景是这样的：订阅了几个画师的推特 ，而且尽管屏蔽了转发和回复，但是还是有很多"废话" ，之前C98中止的时候基本每个订阅的画师都发推表示很伤心，昨天 冬コミ 延期了又集体发推。就是只转发包含图片的推特，而只有文字没有图片的"废话"则过滤掉。  这样也省API次数。

**Comment by Quan666** [comment]
功能描述呢

**Comment by railannad** [comment]
> 功能描述呢

手滑按到回车，在编辑了

**Comment by Quan666** [comment]
https://github.com/Quan666/ELF_RSS/commit/a125119f3ea2c2d5c967e863b067fda145fcacc9
