### ISSUE TITLE
docker 安装方式有个地方写错了

### ISSUE THREAD

**Issue by nekolr** [Quan666/ELF_RSS#50]
在 install.sh 中，原脚本为：
```
docker run --name elfrss -p 8080:8080 -v /app/:/app/ -e TZ=Asia/Shanghai -d elfrss:latest
```

而实际应该为：

```
docker run --name elfrss -p 8080:8080 -v /app/ELF_RSS/:/app/ -e TZ=Asia/Shanghai -d elfrss:latest
```

**Comment by Quan666** [comment]
这并没有错误，这是为了保持docker容器内和宿主机文件路径一致。
不过现在使用base64传送图片，没有必要保持一致了

**Comment by nekolr** [comment]
> 
> 
> 这并没有错误，这是为了保持docker容器内和宿主机文件路径一致。
> 不过现在使用base64传送图片，没有必要保持一致了

以现在的脚本来看，docker容器内的文件和宿主机保持一致的话需要配置为：`-v /app/ELF_RSS/:/app/`，至于为什么会这样，我刚才部署的时候遇到了问题，提示当前目录下没有 bot.py 文件，然后我仔细看了看路径，发现路径映射有问题，我将命令修改为以上命令后就正常了。

具体来说就是，当前目录下有 ELF_RSS 目录，然后你又在根目录下新建了一个 app 目录，然后将整个 ELF_RSS 拷贝到了 app 之下，所以整个项目在宿主机的目录其实为：/app/ELF_RSS。同时，你构建镜像的时候使用的命令是：

```
cd ELF_RSS
docker build -t elfrss:latest .
```

也就是说，你是进到 ELF_RSS 目录中去构建的，接着 Dockerfile 中是这么写的：

```
COPY . /app/
```

这样容器内的结构其实为：app 文件夹包含整个项目

**Comment by Quan666** [comment]
https://github.com/Quan666/ELF_RSS/commit/dd6083b3a8b6bcb753d4e74d3eac347355edaf49 
改了下，你再试试

**Comment by nekolr** [comment]
> 
> 
> [dd6083b](https://github.com/Quan666/ELF_RSS/commit/dd6083b3a8b6bcb753d4e74d3eac347355edaf49)
> 改了下，你再试试

ok了，thanks！

啊，不对，还是报错了：

```
docker: Error response from daemon: create ./: "./" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```

逻辑上是没什么问题的，但是docker推荐使用绝对路径。其实改动最小的就是只修改我上面提到的那里：

```
docker run --name elfrss -p 8080:8080 -v /app/ELF_RSS/:/app/ -e TZ=Asia/Shanghai -d elfrss:latest
```

**Comment by Quan666** [comment]
再试试

**Comment by nekolr** [comment]
> 
> 
> 再试试

tag 有问题吧？cdn下的还是以前的版本，也有可能是缓存
