### ISSUE TITLE
ELF_RSS 抓取图片失败

### ISSUE THREAD

**Issue by chawaa** [Quan666/ELF_RSS#51]
**环境信息：**

运行系统：centos 7.8
Python 版本：3.8.3
ELF_RSS版本：ELF_RSS-2.2.0 最新版
go-cqhttp版本：v1.0.0-beta1 最新版

**`.env.prod `配置文件**

```
IsLinux = true
RSS_PROXY = '127.0.0.1:51837'
```

本地代理（正常）
http://127.0.0.1:51837 或socks://127.0.0.1:51837

**预期行为**

正常发送rss源QQ信息给管理员QQ

**实际行为**

没有发送任何信息，正常生成 订阅名.json文件和imgs文件夹，但下载照片失败。

后台运行窗口报错信息如下：

![image](https://user-images.githubusercontent.com/59247295/112951344-d40cbf00-916d-11eb-9fbd-b4db3ddc004b.png)

![image](https://user-images.githubusercontent.com/59247295/112952209-d3c0f380-916e-11eb-8029-25a9bc9e078c.png)

感谢！！

**Comment by Quan666** [comment]
订阅，信息看看

**Comment by chawaa** [comment]
订阅信息是自建的RSSHUB. 地址 myrsshub/twitter/user/russwest44 ，浏览器正常访问。

showall 正常返回

![image](https://user-images.githubusercontent.com/59247295/112953440-11724c00-9170-11eb-8629-dd61d3a4e720.png)

**Comment by Quan666** [comment]
详细信息

**Comment by chawaa** [comment]
![image](https://user-images.githubusercontent.com/59247295/112954068-a2e1be00-9170-11eb-867b-cd5fe62c0021.png)

是否配置有误？详细信息的代理没开。

**Comment by Quan666** [comment]
代理你没开啊，那不写着false

**Comment by chawaa** [comment]
我重新阅读了一遍文档，现在已经开代理在测试。测试通过后就关闭它，避免再开一个问题。感谢@Quan666

**Comment by chawaa** [comment]
@Quan666 感谢，ELF_RSS 已经运行起来。有几个小问题咨询下：

1. 不支持GIF图片？推文gif图片下载到本地后变成jpg格式;
2. 视频推文，发送到QQ客户端只有封面图，在RSS阅读器可以观看视频。是否缺少什么配置？还是目前暂不支持视频？
![image](https://user-images.githubusercontent.com/59247295/112965902-4a182280-917c-11eb-8925-54879883ba49.png)

**Comment by Quan666** [comment]
目前还不支持视频，GIF
后面我支持下
