### ISSUE TITLE
同订阅多个群组会有部分发送失败

### ISSUE THREAD

**Issue by DreamGallery** [Quan666/ELF_RSS#517]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

ELF_RSS：2.6.23
Python：3.12.3
nonebot：2.3.2

### 如何复现

我有一个订阅，打算推送给多个群组，但是好像只要一个订阅超过3个推送对象就有可能会有群组发送失败（超时），有的时候图片加载也会不完整，不知道是不是也有风控的原因在里面。

### 实际行为

上次我想推送BiliBili的动态到6个群，但是只有两个群发送成功了，是否有办法优化，比如同一个订阅的几个消息推送对象之间能间隔几秒发送？报错信息因为screen能存的有限，等下次再补充。我现在是尝试将同一个订阅分成了三组，不知道有没有作用。
看了其他的issue，好像当前的重试机制是得全部对象推送失败才会重试。推送的RSS服务是自己搭建的，那个应该没有什么问题。

**Comment by Quan666** [comment]
应该是风控

**Comment by DreamGallery** [comment]
我现在两个群一个订阅运行了一段时间，倒是挺稳定的。另外就是又遇到一个报错来汇报一下。
情况是这样的，我有一个推特的12小时间隔的推送订阅，因为某些原因我重启了一下我的机器人，也的确成功推送了那些更新内容。不过机器人的日志里出现了这样的错误。
![image](https://github.com/user-attachments/assets/40e1b23d-826d-4f94-a9c9-410710b4197a)
稍微去看了一下代码，不过我不清楚到底发送的这个item是什么内容，大概不影响使用？不过既然报错了还是说一下。
