### ISSUE TITLE
rss_class 返回的地址中包含双斜杠

### ISSUE THREAD

**Issue by baka23** [Quan666/ELF_RSS#527]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

elf-rss 2.6.23
nonebot2 2.3.2
python 3.12.3
linux 6.6.38

### 如何复现

正常部署rsshub，nonebot和elf-rss就会遇到

### 期望行为

返回的地址中不含双斜杠

urllib.parse 的 urljoin 函数可以正常处理拼接地址时双斜杠的问题

### 实际行为

![Screenshot_20240831-175534](https://github.com/user-attachments/assets/898b426d-7edc-4c19-b7e1-698452f83755)
![Screenshot_20240831-175639](https://github.com/user-attachments/assets/c2f1133f-d7a1-4cab-a8e5-faac0229e26b)

**Comment by Quan666** [comment]
你添加订阅的命令呢

**Comment by baka23** [comment]
/add bilistat_sqd bilibili/user/dynamic/38882086/disableEmbed=true

我还有哪些遗漏的部分

**Comment by baka23** [comment]
补充一些信息
有可能是 pydantic 导致的问题

pydantic-2.8.2
pydantic_core-2.20.1

附：
我在 .env.prod 中填写的地址

![Screenshot_20240831-203959~2](https://github.com/user-attachments/assets/5129e6df-6f5c-4eed-8c11-5728afbd53d8)

elf-rss 启动时读取到的地址

![Screenshot_20240831-203930~3](https://github.com/user-attachments/assets/31431855-eb80-487a-8b5d-962e38352411)

**Comment by Quan666** [comment]
URL/开头试试

**Comment by baka23** [comment]
恕我冒昧

rss_class.py 中 get_url 只考虑到了订阅地址开头可能带 "/" 但没有考虑到 rsshub 地址末尾带 "/" 的情况，即使这不是被用户添加的

**Comment by Quan666** [comment]
你可以考虑帮着修复下
我已经不再使用这个项目了

**Comment by baka23** [comment]
还是要说句谢谢，我要去学一下怎么提pr了）
