### ISSUE TITLE
请教关于抓取失败的原因

### ISSUE THREAD

**Issue by YokiiroBW** [Quan666/ELF_RSS#54]
大佬您好，我也是这方面的小白， 第一次接触这个，按照教程部署好了，命令也都可以正常使用，但是订阅就是抓取失败，我试过推特和终点站的源，都是抓取失败，但是我把链接复制到我的游览器里又可以打开，只是有时候更新比较慢，所以我想请教下是为什么，梯子用的是SSR，已经打开全局模式了。
![image](https://user-images.githubusercontent.com/82425598/114723103-f78a5900-9d6c-11eb-8397-34ee87f1ab3c.png)

**Comment by Quan666** [comment]
配置文件里面要配置你代理的地址端口

**Comment by Quan666** [comment]
以及单个订阅开启代理

**Comment by YokiiroBW** [comment]
非常感谢，这个问题已经解决了，但是我绑定了自己的推特测试后，不管我转推还是发推，后台都没有反应，我把time调成1，第一次是显示（第一次抓取成功），再往后就全部都是没有新信息。这个是RSS的问题么，有没有好的解决办法呢
![G4H81SJ%3GAOB7I6@UA GAJ](https://user-images.githubusercontent.com/82425598/114809099-212e9900-9ddc-11eb-806c-522b09bd7b7c.png)

**Comment by nekolr** [comment]
> 
> 
> 非常感谢，这个问题已经解决了，但是我绑定了自己的推特测试后，不管我转推还是发推，后台都没有反应，我把time调成1，第一次是显示（第一次抓取成功），再往后就全部都是没有新信息。这个是RSS的问题么，有没有好的解决办法呢
> ![G4H81SJ%3GAOB7I6@UA GAJ](https://user-images.githubusercontent.com/82425598/114809099-212e9900-9ddc-11eb-806c-522b09bd7b7c.png)

直接拿着你订阅的 rsshub 链接查查，没有新内容的话应该就是 rsshub 那边抓取频率的问题了，可以尝试自己搭建 rsshub。

**Comment by YokiiroBW** [comment]
好的感谢

**Comment by lancer-wang** [comment]
> 配置文件里面要配置你代理的地址端口
我配置了代理地址为什么还是出错,不加http的也试过了
![image](https://user-images.githubusercontent.com/69783837/115519350-b4277180-a2bb-11eb-8e5b-6f8b2a4745c4.png)
![image](https://user-images.githubusercontent.com/69783837/115519580-ea64f100-a2bb-11eb-9736-fc4b3aa9776e.png)
![image](https://user-images.githubusercontent.com/69783837/115519593-edf87800-a2bb-11eb-9f12-98586413ea22.png)
