### ISSUE TITLE
cookie无法正常添加

### ISSUE THREAD

**Issue by ModChino** [Quan666/ELF_RSS#558]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

ELF_RSS = v2.6.25
napcat = 最新版
python = 3.10.15
OS = Ubuntu 24.04.1 LTS

### 列出安装的 Python 包

aiodns==3.2.0
aiohappyeyeballs==2.4.3
aiohttp==3.10.10
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.6.2.post1
APScheduler==3.10.4
argcomplete==3.5.1
arrow==1.3.0
async-timeout==4.0.3
attrs==24.2.0
bbcode==1.1.0
beautifulsoup4==4.12.3
binaryornot==0.4.4
Brotli==1.1.0
cachetools==5.5.0
cashews==7.3.2
certifi==2024.8.30
cffi==1.17.1
chardet==5.2.0
charset-normalizer==3.4.0
click==8.1.7
cookiecutter==2.6.0
cssselect==1.2.0
deep-translator==1.11.4
distlib==0.3.9
emoji==2.14.0
exceptiongroup==1.2.2
fastapi==0.115.4
feedparser==6.0.11
filelock==3.16.1
frozenlist==1.5.0
h11==0.14.0
httpcore==1.0.6
httptools==0.6.4
httpx==0.27.2
idna==3.10
ImageHash==4.3.1
Jinja2==3.1.4
loguru==0.7.2
lxml==5.3.0
magneturi==1.3
markdown-it-py==3.0.0
MarkupSafe==3.0.2
mdurl==0.1.2
msgpack==1.1.0
multidict==6.1.0
nb-cli==1.4.2
nonebot-adapter-onebot==2.4.6
nonebot-plugin-apscheduler==0.5.0
nonebot2==2.4.0
noneprompt==0.1.9
numpy==2.1.3
packaging==24.2
PikPakAPI==0.1.10
pillow==10.4.0
platformdirs==4.3.6
prompt_toolkit==3.0.48
propcache==0.2.0
pycares==4.4.0
pycparser==2.22
pydantic==2.9.2
pydantic_core==2.23.4
pyfiglet==1.0.2
Pygments==2.18.0
pygtrie==2.5.0
pyquery==2.0.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-qbittorrent==0.4.3
python-slugify==8.0.4
pytz==2024.2
PyWavelets==1.7.0
PyYAML==6.0.2
requests==2.32.3
rich==13.9.4
scipy==1.14.1
sgmllib3k==1.0.0
six==1.16.0
sniffio==1.3.1
soupsieve==2.6
starlette==0.41.2
tenacity==8.5.0
text-unidecode==1.3
tinydb==4.8.2
tomli==2.1.0
tomlkit==0.13.2
types-python-dateutil==2.9.0.20241003
typing_extensions==4.12.2
tzlocal==5.2
urllib3==2.2.3
userpath==1.9.2
uvicorn==0.32.0
uvloop==0.21.0
virtualenv==20.27.1
watchfiles==0.24.0
wcwidth==0.2.13
websockets==13.1
yarl==1.17.1

### 如何复现

添加cookie的时候会报错
指令：
`elf 添加cookies xxx_fanbox p_ab_id=5;FANBOXSESSID=xxxx;__cf_bm=xxxx;p_ab_d_id=xxxxx;p_ab_id_2=1;privacy_policy_agreement=7;privacy_policy_notification=0`

### 期望行为

希望修复，因为部分内容需要cookie才能获取。

### 实际行为

![ede3a512de874491a9d708fb6bc04898](https://github.com/user-attachments/assets/b95b895f-2917-4971-aaa7-95495c591cfa)

**Comment by Quan666** [comment]
https://github.com/Quan666/ELF_RSS/tree/Quan666-patch-3
试试这个分支
改动：https://github.com/Quan666/ELF_RSS/pull/559/files

**Comment by ModChino** [comment]
> https://github.com/Quan666/ELF_RSS/tree/Quan666-patch-3 试试这个分支 改动：https://github.com/Quan666/ELF_RSS/pull/559/files

感谢 已添加成功
