### ISSUE TITLE
mirai-native图片处理出错

### ISSUE THREAD

**Issue by mengshouer** [Quan666/ELF_RSS#6]
rsshub.py处理图片出错，mirai-native的图片是不落地的，但是我看代码cq码处理的是本地的图片，所以会报图片走丢啦！

**Comment by Quan666** [comment]
> rsshub.py处理图片出错，mirai-native的图片是不落地的，但是我看代码cq码处理的是本地的图片，所以会报图片走丢啦！

我看了他的api文档，可以发送绝对路径下的图片。
麻烦将错误日志发出来，以及复现步骤

**Comment by mengshouer** [comment]
dbq,是我瞎了，移植到自己的Nonebot上面config少了个参数(没问题了
