### ISSUE TITLE
使用手册好像需要更新

### ISSUE THREAD

**Issue by Catoverflow** [Quan666/ELF_RSS#62]
现在的 go-cqhttp 配置文件已经是 yaml 格式了，而且按照手册在部署过程中经常出现各种问题比如
`ModuleNotFoundError: No module named 'nonebot.plugins.nonebot_plugin_apscheduler'`
使用 `nb install` 时的参数也不一样了，并且没有引导界面
还经常出现 `Value for scheme.scripts does not match`（参看[这里](https://github.com/pypa/pip/issues/9617)）的问题，应该是和 Python 版本有关
本机环境是 Linux 5.11.16-arch1-1 Python 3.9.4
请问能否更新一下手册呢？（也请教一下上面的模块问题如何解决）

**Comment by Quan666** [comment]
https://github.com/Quan666/ELF_RSS/wiki/%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B
已经更新

**Comment by Quan666** [comment]
按照我的教程走是不需要你手动输入 `nb install`  的
