### ISSUE TITLE
<a>标签处理问题

### ISSUE THREAD

**Issue by mengshouer** [Quan666/ELF_RSS#8]
https://github.com/Quan666/ELF_RSS/blob/083d7baeb34f084ca25166d15751a99a258d29ea/include/plugins/RSSHub/rsshub.py#L243
span标签处理不全，前面应该改为<span.*?>？
https://github.com/Quan666/ELF_RSS/blob/083d7baeb34f084ca25166d15751a99a258d29ea/include/plugins/RSSHub/rsshub.py#L257
a标签匹配某些微博的时候，a标签中有多余的span标签，导致re.sub匹配的re.escape(a)内容和rss_str不一致，删不干净，可以考虑把处理span标签放在https://github.com/Quan666/ELF_RSS/blob/083d7baeb34f084ca25166d15751a99a258d29ea/include/plugins/RSSHub/rsshub.py#L238
之前？或者修改a标签的匹配方式？

示例微博:/weibo/user/1797798792

**Comment by Quan666** [comment]
有处理前的文本吗？我看下怎么改比较合适

**Comment by mengshouer** [comment]
------原文本------
<div>
<p>维护现已开始。<br/></p><blockquote> - 转发 <a href="https://weibo.com/1797798792" target="_blank">@最终幻想14</a>: <a href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E6%9C%80%E7%BB%88%E5%B9%BB%E6%83%B314%23&amp;isnewpage=1" data-hide=""><span class="surl-text">#最终幻想14#</span></a><a href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23FF14%23" data-hide=""><span class="surl-text">#FF14#</span></a>  《8月18日全区全服更新维护公告》<br/>我们将于8月18日12:00-16:00对全区全服进行更新维护 。请各位冒险者互相转告，合理安排游戏时间，提前在安全区域下线。如遇特殊情况，维护时间将可能延长，请关注我们的官网公告。查看详情：<a data-url="http://t.cn/A6URZCWd" href="http://t.cn/A6URZCWd" data-hide="">网页链接</a><br/>☆预计维护时间：2020年8月18日12：00-16：00☆  <br/>☆维护范围：全区全服☆<br/>☆本次维护内容☆<br/>-更新客户端版本至Ver. 2020.08.06.0000.0000（5.21版本）<br/>- 「宇宙和音」、「海猫茶屋」取消新服务器状态和新服务器优待<br/>-所有服务器设置为动态开启/关闭新角色创建。<img src="https://wx4.sinaimg.cn/large/6b283b88gy1ghtscqqozxj20ly05wwfl.jpg" referrerpolicy="no-referrer"/><br/><br/></blockquote>
</div>

-----re.escape(str(a))文本------
<a\ href="https://m\.weibo\.cn/search\?containerid=231522type%3D1%26t%3D10%26q%3D%23%E6%9C%80%E7%BB%88%E5%B9%BB%E6%83%B314%23\&amp;isnewpage=1"\ data\-hide=""><span\ class="surl\-text">\#最终幻想14\#</span></a>

------实际str文本-----
<a href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E6%9C%80%E7%BB%88%E5%B9%BB%E6%83%B314%23&amp;isnewpage=1" data-hide=""><span class="surl-text">#最终幻想14#</a>

**Comment by mengshouer** [comment]
https://share.weiyun.com/JWM6e5uS

**Comment by Quan666** [comment]
有群，984827132

**Comment by Quan666** [comment]
已经修复 https://github.com/Quan666/ELF_RSS/commit/dbac5337f66c786ed97c286a503840871e6ffc7f
